coord: only compact sqlite ts bindings once every 15 min/source
MaterializeInc/materialize pull request #10731
Opened 2022-02-16 20:57 UTC by ruchirK

### Motivation

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

2022-02-16 20:59 UTC, ruchirK commented
This is a super wip draft but I'm putting it up to see if you guys think an approach like this is morally in the right direction for making sqlite compaction less terrible. I'll also include test results and things like that

2022-02-17 08:19 UTC, antiguru commented
With this change, the test from #10582 passes on my machine with 8 workers.

With 64 workers, it surfaces another previously unreported problem :)
```
cargo run --release --bin materialized -- --workers 64 --timestamp-frequency=100ms

    Finished release [optimized + debuginfo] target(s) in 0.26s
     Running `target/release/materialized --workers 64 --timestamp-frequency=100ms`
=======================================================================
Thank you for trying Materialize!

We are interested in any and all feedback you have, which may be able
to improve both our software and your queries! Please reach out at:

    Web: https://materialize.com
    GitHub issues: https://github.com/MaterializeInc/materialize/issues
    Email: support@materialize.com
    Twitter: @MaterializeInc
=======================================================================

materialized v0.20.1-dev (e81992d67) listening on 0.0.0.0:6875...
2022-02-17T08:17:43.716570Z ERROR librdkafka: THREAD [thrd:app]: Unable to create broker thread
SIGBUS or SIGSEGV while handling SIGSEGV or SIGBUS
(maybe a stack overflow while allocating?)
[1]    243251 IOT instruction  MZ_LOG_FILTER=librdkafka=info cargo run --release --bin materialized --  64
```

2022-02-17 13:07 UTC, ruchirK commented
So my thought was that it makes sense that this would pass the original test, as we likely don't do any compactions in the first 15 minutes. I was going to let it run and measure the latency of doing compaction and check to make sure that latency stays around 20 - 30 ms. Its not worth if that latency is significantly higher after batching up compactions

Re the failure with 64 workers: that's a mystery :) How many cores does the box have?

2022-02-17 13:50 UTC, antiguru commented
The failure with 64 workers is not a mystery! It's simply that the process' vspace is capped at 200GiB and it tries to exceed this, which results in thread creation errors/malloc failing. And when malloc fails, our signal handler ooms again, which causes the unhelpful error message. Also, at this point it was like 25k threads and 50k FDs :/ The way we exercise librdkafka is not very resource friendly.

2022-02-17 18:03 UTC, philip-stoev requested changes
This needs to be made configurable for testing purposes -- otherwise it will not get exercised at all. So either a stand-alone option for the materialized binary, or it needs to be some multiple of the timestamp-interval, so that when the timestamp-interval is set to 100ms, it happens every few seconds or so.

2022-02-28 13:05 UTC, frankmcsherry commented
Could this become "compact when the number of new insertions reaches the previously compacted size", to get work efficiency?

2022-02-28 14:14 UTC, ruchirK commented
> Could this become "compact when the number of new insertions reaches the previously compacted size", to get work efficiency?

yes! I just did the quickest thing to prototype

2022-03-10 16:57 UTC, ruchirK commented
Closing this as it is obsolete after #10941 . We may still want to rate limit the number of writes to sqlite but for now things seem fine

2022-03-10 16:57 UTC, closed without merging