doc: Add Ruby pg guide
MaterializeInc/materialize pull request #11376
Opened 2022-03-24 13:27 UTC by bobbyiliev

### Motivation

This adds a Ruby guide that follows the format of the [Node.JS](https://materialize.com/docs/guides/node-js/) and [PHP](https://materialize.com/docs/guides/php-pdo/) and Golang guides that we already have.

2022-04-04 20:42 UTC, ruf-io requested changes
Two high-level questions/requests:

1. Is it necessary to include `pp`? 
2. Switch to hash style for connect syntax

2022-04-04 20:42 UTC, ruf-io commented on doc/user/content/guides/ruby.md
> +conn = PG.connect("127.0.0.1", 6875, '', '', "materialize", "materialize", "materialize")
switch to hash style

2022-04-05 08:53 UTC, bobbyiliev commented on doc/user/content/guides/ruby.md
> +require 'pp'
Yep good point! Better to keep it consistent. 

Initially, I used `pp` to inspect the `PG::Result class`. As if you do `puts result` you would get `#<PG::Result:0x000000015a100b48>` which does not give you much information, where as with `pp` you would get information about the status and etc: `#<PG::Result:0x0000000125087980 status=PGRES_COMMAND_OK ntuples=0 nfields=0 cmd_tuples=0>`.

But I could just have used the `.inspect` method with `puts` as follows: `puts result.inspect` to do the same.

Just submitted the changes so it is consistent throughout the doc.

2022-04-13 13:12 UTC, morsapaes commented on doc/user/content/guides/ruby.md
> +Materialize is **PostgreSQL-compatible**, which means that Ruby applications can use any existing PostgreSQL client to interact with Materialize as if it were a PostgreSQL database. In this guide, we
```suggestion
Materialize is **PostgreSQL-compatible**, which means that Ruby applications can use any existing PostgreSQL client to interact with Materialize as if it were a PostgreSQL database. In this guide, we'll use  [`pg` gem](https://rubygems.org/gems/pg/) to connect to Materialize and issue PostgreSQL commands.
```

2022-04-13 13:16 UTC, morsapaes approved these changes

2022-04-13 13:16 UTC, morsapaes commented on doc/user/content/guides/ruby.md
> +For more details, see the  [`exec` instancemethod](https://rubydoc.info/gems/pg/0.10.0/PGconn#exec-instance_method) documentation.
```suggestion
For more details, see the  [`exec` instance method](https://rubydoc.info/gems/pg/0.10.0/PGconn#exec-instance_method) documentation.
```

2022-04-13 15:06 UTC, ruf-io approved these changes

2022-04-14 14:06 UTC, merged