doc/developer: add kleppmann's book to required reading list
MaterializeInc/materialize pull request #11464
Opened 2022-03-30 03:38 UTC by benesch

Would anyone like to suggest a set of specific chapters to focus on?

----

Per recommendation from @umanwizard.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

2022-03-30 03:48 UTC, elindsey approved these changes

2022-03-30 14:07 UTC, umanwizard commented on doc/developer/reading.md
> +* Designing Data-Intensive Applications [marketing website](https://dataintensive.net)
Did you mean to put the link in brackets like the other ones?

2022-04-01 13:42 UTC, frankmcsherry requested changes
Can we move it to "recommended reading"? I would actually like people to read the other things on the list, but obliging them to read an entire book seems to dilute the urgency of other items.

2022-04-01 13:57 UTC, benesch commented
Ha! @umanwizard and I were just talking about that yesterday. I was going to go through and annotate each item with some context, including at which moment the reading is recommended or required. I’ll ping you for review when I’m done!

2022-05-04 15:13 UTC, merged