test and document confluent ssl options for sinks
MaterializeInc/materialize pull request #11634
Opened 2022-04-06 23:45 UTC by guswynn

I noticed we don't actually do the same suite of tests for sinks as sources, so I added tests.

Additionally, the options listing was very out of date. It lacked the section on CSR options, and the source version has a huge amount of information and examples about the various schemes. Instead of copying, I just linked to and removed the old tables. We could eventually split kafka + csr ssl into its own page and inline it into both sinks and sources, maybe

Also, I think `username` and `password` arent kafka options anymore? so i removed that table too

cc @morsapaes who did the big kafka sources docs refactor.

### Motivation

tests and doc improvement

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.

### Release notes

None

2022-04-08 14:02 UTC, morsapaes requested changes

2022-04-08 18:11 UTC, guswynn commented on doc/user/content/sql/create-sink.md
> +Sinks use the same ssl and authentication scheme as sources. Please see
is that what a "partial" is? I can try to figure out how that works next week!

2022-04-11 12:10 UTC, morsapaes approved these changes
I forgot how appalling the current sink documentation is, so let's roll with this until we effectively create a dedicated Kafka sink page; it'll be easier to reuse the existing content for sources then. I'll keep a mental note!

2022-04-11 12:10 UTC, morsapaes commented on doc/user/content/sql/create-sink.md
> +`security_protocol`  | `text`     | Use [`ssl`](#ssl-and-authentication) or, for [Kerberos](#ssl-and-authentication), `sasl_plaintext`, `sasl-scram-sha-256`, or `sasl-sha-512` to connect to the Kafka
```suggestion
`security_protocol`  | `text`     | Use [`ssl`](#authentication) or, for [Kerberos](#authentication), `sasl_plaintext`, `sasl-scram-sha-256`, or `sasl-sha-512` to connect to the Kafka cluster.
```

2022-04-11 12:10 UTC, morsapaes commented on doc/user/content/sql/create-sink.md
> +_with&lowbar;options_ | Options affecting Materialize's connection to Kafka. For more detail, see [SSL and Authentication](#ssl-and-authentication).
```suggestion
_with&lowbar;options_ | Options affecting Materialize's connection to Kafka. For more detail, see [SSL and Authentication](#authentication).
```

2022-04-11 12:10 UTC, morsapaes commented on doc/user/content/sql/create-sink.md
> +#### SSL and Authentication
```suggestion
#### Authentication
```

2022-04-11 12:10 UTC, morsapaes commented on doc/user/content/sql/create-sink.md
> +[those docs](/sql/create-source/kafka/#authentication) for details and examples/
```suggestion
Kafka sinks support the same authentication scheme and options as Kafka sources (`SSL`, `SASL`). Check the [Kafka source documentation](/sql/create-source/kafka/#authentication) for more details and examples.
```

2022-04-11 13:55 UTC, merged