storage: implement abelian and Codec64 for MzOffset
MaterializeInc/materialize pull request #13020
Opened 2022-06-09 18:58 UTC by guswynn

Closes https://github.com/MaterializeInc/materialize/issues/11954

@petrosagg mentioned on that pr that we could clean the reclock operator up by just making `MzOffset` implement `Abelian`, so this is that implementation! it panics if the `Neg` impl is used. The main issue is that we now are locked into the fact that offsets are `Codec64`, but we had the requirement implicitly before

### Motivation

   * This PR refactors existing code.

### Testing

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
CI

### Release notes
None

2022-06-09 19:16 UTC, cjubb39 requested changes
I'm down with the part of this that has `MzOffset` implementing `Codec64` -- that makes sense and I don't think we realistically should anticipate the size of that changing.

I think we should keep the explicit unwraps/expects inline as they are rather than implementing a trait that, if ever used, will panic.  `MzOffset` is _not_ an Abelian group so I don't think we should label it as such.  That seems like just laying the groundwork for futures bugs / panics

2022-06-10 15:42 UTC, guswynn commented
@cjubb39 now this only implements traits that make sense for `MzOffset`! This is clean because @ruchirK recently implemented `Semigroup` for unsigned ints!

2022-06-14 15:46 UTC, cjubb39 approved these changes
this looks good!  Thanks for making the update.

(if you want to add back the Monoid impl, I think that's okay since I do think that's appropriate for this type! even though it's not strictly necessary here)

2022-06-14 16:55 UTC, guswynn commented
@cjubb39 ill add the minimum required impls for now!

2022-06-14 16:55 UTC, merged