[sinks] More error handling in the Kafka sink
MaterializeInc/materialize pull request #14965
Opened 2022-09-23 20:17 UTC by bkirwi

Right now the Kafka sink handles errors fairly quietly. This means any persistent errors don't always percolate up, and if the Kafka client gets into a bad state it may never get unstuck.

The goal of this PR is to switch to being noisy about errors, including possibly panicing to force a restart of the `storaged` instance. The idea is that being crashy is better than getting into a "zombie" state where we're up but not making progress, and we can follow up in the future to improve reporting.

### Motivation

We have a number of related bugs under #11503, including stuff like #14098.

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-protobuf` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

2022-09-26 18:23 UTC, bkirwi commented
This is intentionally slightly maximalist: for example, I think it would be safe to loop if we fail to fetch the latest progress record, since we haven't done anything with the main producer instance yet. I think this is probably the right call at least while we don't have other good mechanisms to surface errors, though.

2022-09-27 13:37 UTC, aljoscha approved these changes
I like it! Being more crashy here will show up, say, in the Kubernetes restart metrics and such, so people should be more likely to notice.

2022-09-27 13:44 UTC, cjubb39 requested changes
This seems like we'll panic any time we hit an rdkafka error (even if we've recovered from it due to the logic in `retry_on_txn_error`.

What do you think of an approach where, if we hit an error we know we _cannot_ recover from, we set an error on a new field on `KafkaSinkState` (which would mean that shutdown flag is now only set when the `KafkaSinkToken` is dropped) and then at the top of the function, after checking the shutdown flag, we panic if that error is set?

I think we can get a lot of the benefit of panicking on error without basically giving up on any sort of error recovery at all

2022-09-27 15:54 UTC, bkirwi commented
> This seems like we'll panic any time we hit an rdkafka error (even if we've recovered from it due to the logic in retry_on_txn_error.

That doesn't match my understanding -- AFAICT `retry_on_txn_error` [will return success if any of the attempts succeed](https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/sink/kafka.rs#L557-L558), so we only bail out if we run out of retries. And at that point, I'd be comfortable without another round of error handling. Does that look right based on the code there, or what am I missing?

> What do you think of an approach where, if we hit an error we know we cannot recover from, we set an error on a new field on KafkaSinkState (which would mean that shutdown flag is now only set when the KafkaSinkToken is dropped) and then at the top of the function, after checking the shutdown flag, we panic if that error is set?

That strikes me as mostly equivalent, assuming we immediately end the async-op when we hit an unrecoverable error. (Which seems like the safe thing!) What do you see as the tradeoffs between the two approaches?

2022-09-27 16:13 UTC, cjubb39 commented
> AFAICT retry_on_txn_error [will return success if any of the attempts succeed](https://github.com/MaterializeInc/materialize/blob/main/src/storage/src/sink/kafka.rs#L557-L558), so we only bail out if we run out of retries

What you write is correct -- though it is not correct so say that we only return an error if hit an unrecoverable error.  Just below your link, if we hit a TransactionError that requires an abort -- and then the abort succeeds, we do _not_ set the shutdown flag but return an error.  After getting that error, we could reasonably continue on from the top of the `async_op`.

> That strikes me as mostly equivalent, assuming we immediately end the async-op when we hit an unrecoverable error. (Which seems like the safe thing!) What do you see as the tradeoffs between the two approaches?

If one of these functions returning an error indicated that we hit an unrecoverable error, I'd be with you!  If you don't like the exit then handle at the top approach (which, fair enough!), I'd be onboard with amending `bail_err` to 1) print the error and return if the shutdown/error flag is not set (meaning we did successfully abort the transaction); or 2) panic if the shutdown/error flag is set -- so that we only restart from the top if we think we have a chance of running again

2022-09-28 21:07 UTC, cjubb39 approved these changes
We chatted a bunch offline and I'm okay with this change given that we'll plan to keep an eye on perf downsides.  I'll summarize a bit of our conversation in case we come back to look at this in the future:
- we want to take the approach of "crash unless we know for sure we're making progress".  The current code is more akin to "only crash if we know for sure we can't make progress"
- there's more state than I had initially considered.  The number of questions about what happens to messages in flight when a transaction is aborted makes us uneasy enough.  It's doable if we needed but we don't think we need
- the cost of restarting is currently likely relatively high -- but so long as we keep our eyes on the perf impact, we should be okay.
- there are two big fixes we could likely make in order to make restarts faster: (1) not re-reading the whole snapshot from persist if we know we'll throw it away; (2) compacting the progress topic output

All that to say: I'm convinced that we can keep the potential perf impact enough under control that the simplification in thinking about error handling is worth it

2022-09-29 20:13 UTC, merged