doc/user: [Kafka sources] add confluent schema registry sasl
MaterializeInc/materialize pull request #15486
Opened 2022-10-17 23:35 UTC by joacoc

### Motivation

This PR adds the `Confluent Schema Registry` SASL plain mechanism to the Kafka source guide.

![Screen Shot 2022-10-17 at 20 31 45](https://user-images.githubusercontent.com/11491779/196302433-d6594f5b-45d3-4437-abfa-3782c2b4e0ff.png)

### Tips for reviewer

It works well with Confluent Schema Registry, but I haven't tested if it works with local deployments of the confluent schema registry.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

2022-10-18 09:38 UTC, morsapaes commented
What makes this `SASL` versus `HTTP Basic`? Are we inheriting the `SASL` auth for Schema Registry if the broker connection is configured to use `SASL`? Asking because we refer to just using `username` and `password` as HTTP basic authentication in the [`CREATE CONNECTION` page](https://materialize.com/docs/sql/create-connection/#confluent-schema-registry).

2022-10-18 16:38 UTC, joacoc commented
@morsapaes `SASL` is, in fact, wrong. After checking the CSSR client, I can say it makes a basic auth request:

https://github.com/MaterializeInc/materialize/blob/f4ed657b7034660c28ef82083214405d7d929bca/src/ccsr/src/client.rs#L54

2022-10-18 23:04 UTC, morsapaes requested changes

2022-10-18 23:04 UTC, morsapaes commented on doc/user/content/sql/create-source/kafka.md
> +{{< tab "Basic Authentication">}}
```suggestion
{{< tab "Basic HTTP Authentication">}}
```

2022-10-18 23:04 UTC, morsapaes commented on doc/user/content/sql/create-source/kafka.md
> +{{< tab "Basic Authentication">}}
For [standardization](https://www.rfc-editor.org/rfc/rfc7617).

2022-10-18 23:04 UTC, morsapaes commented on doc/user/content/sql/create-source/kafka.md
> +CREATE CONNECTION csr_sasl
```suggestion
CREATE CONNECTION csr_basic_http
```

2022-10-19 14:57 UTC, morsapaes approved these changes

2022-10-19 15:26 UTC, merged