sql: add right_inverse to LazyUnaryFunc
MaterializeInc/materialize pull request #15591
Opened 2022-10-21 16:35 UTC by sploiselle

The optimizer would like to use the right inverse of cast functions to make index selection more powerful, e.g. if a column reference is cast to some type to make it comparable to a literal, we can instead cast the literal to the column's type, making it possible to an index on that column.

### Motivation

This PR adds a known-desirable feature. Discussed in #15476

### Tips for reviewer

@petrosagg Tagging you just because you worked on the macro; if you see any areas to clean that up, very welcome to suggestions.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Improve Materialize's ability to use indexes when comparing column expressions to literal values, e.g. `SELECT * FROM table_foo WHERE col_a = 'hello'`, particularly cases where `col_a` was of type `VARCHAR`.

2022-10-21 17:42 UTC, ggevay requested changes

2022-10-21 17:42 UTC, ggevay commented on src/expr/src/scalar/func/impls/int16.rs
> +    #[preserves_uniqueness = false]
Btw. it's already true on `neg_int64`.

2022-10-21 17:42 UTC, ggevay commented on src/expr/src/scalar/func/impls/mz_timestamp.rs
>      fn cast_int64_to_mz_timestamp(a: i64) -> Result<Timestamp, EvalError> {
not reversed

2022-10-21 17:42 UTC, ggevay commented on src/expr/src/scalar/func/impls/mz_timestamp.rs
>      fn cast_int32_to_mz_timestamp(a: i32) -> Result<Timestamp, EvalError> {
not reversed

2022-10-21 17:42 UTC, ggevay commented on src/expr/src/scalar/func/impls/timestamp.rs
>      fn cast_timestamp_tz_to_timestamp(
not reversed

2022-10-21 17:42 UTC, ggevay commented on src/expr/src/scalar/func/impls/timestamp.rs
>      fn cast_timestamp_to_time(a: CheckedTimestamp<NaiveDateTime>) -> NaiveTime {
not reversed

2022-10-21 17:42 UTC, ggevay commented on src/expr/src/scalar/func/impls/timestamp.rs
>      fn cast_timestamp_tz_to_time(a: CheckedTimestamp<DateTime<Utc>>) -> NaiveTime {
not reversed

2022-10-21 17:43 UTC, ggevay commented on src/expr/src/scalar/func/impls/uint32.rs
> +        to_unary!(super::CastNumericToInt32)
signedness mismatch

2022-10-21 17:45 UTC, ggevay commented on src/expr/src/scalar/func/impls/uint64.rs
> +    fn cast_uint64_to_int32(a: u64) -> Result<i32, EvalError> {
not reversed and signedness mismatch

2022-10-21 18:40 UTC, sploiselle commented on src/expr/src/scalar/func/impls/int16.rs
> +    #[preserves_uniqueness = false]
Good catch; I was lazy about modifying `preserves_uniqueness`; if it was false I mostly left it as false. Will amend these.

2022-10-23 18:00 UTC, ggevay approved these changes
Thanks a lot!

I have just two minor comments left for this PR.

And one more thing (which I might address in a follow-up PR): I'm thinking about the name `right_inverse`. It's not actually a right inverse in those cases where the specified "right inverse" has `preserves_uniqueness = false`. For example, it's not a right inverse for `cast_int32_to_float64`, because `cast_float64_to_int32` rounds, so it can happen that casting from a float64 to int32 and then back to float64 yields a different float64 from the original number that we started with, thus violating the "right inverse" property. (This is why the optimizer always checks `preserves_uniqueness` before actually doing the inverse cast transformation.)

So the situation is the following:
- It's a _right inverse_ where the currently specified `right_inverse` preserves uniqueness. (I think when @aalexandrov suggested the name `right_inverse`, he thought that we will put it only on these functions.)
- It's a _left inverse_ where the function itself preserves uniqueness.
- It's both a _left inverse_ and a _right inverse_ (which is simply _inverse_) where both preserve uniqueness. (e.g., `bit_not_int64` is both a right and left inverse of itself)

So I would say let's just call it `inverse`, and explain these things in the doc comment, that our `inverse` doesn't always correspond to the mathematical notion of "inverse" in itself, only together with checking `preserves_uniqueness`. (And one more thing one needs to keep in mind is that our `preserves_uniqueness` doesn't cover error results, i.e., it can happen that casting two different int64 to int32 yield the same error result if both int64s are too big for int32.)

If you agree, I'll do these renaming and comment changes in a follow-up PR.

2022-10-23 18:00 UTC, ggevay commented on src/expr/src/scalar/func/impls/timestamp.rs
> +    #[preserves_uniqueness = false]
I think @mjibson says [here](https://github.com/MaterializeInc/materialize/pull/15476#issuecomment-1282592187) that this should be `true`.

2022-10-24 14:50 UTC, sploiselle commented
@ggevay ptal, notably [my expansion of the doc comment](https://github.com/MaterializeInc/materialize/pull/15591/files#diff-6803539c802e2aee474fb1c0fab29db55cfb9e4d4bd3797509b7f18971f1480bR3408)

2022-10-24 14:56 UTC, ggevay commented
Thanks for the renaming and doc comment extension! Everything looks perfect now!

2022-10-24 20:12 UTC, merged