Protect `Subscribe` against computed-based OOMs
MaterializeInc/materialize pull request #15703
Opened 2022-10-26 13:52 UTC by frankmcsherry

A revised version of #15347 that avoids a gnarly rebase.

---

Prevent environmentd OOMs when using SUBSCRIBE.

This PR modifies computed to only return SubscribeResponse with at most a specified limit on the number of bytes in records. This allows environmentd to safely receive the results, and move forward with them or report an error if the response did not fit in the bounds.

Fixes https://github.com/MaterializeInc/materialize/issues/15202

### Motivation

  * This PR fixes a recognized bug.

### Tips for reviewer

This PR is identical to #15347 which has undergone review and had some amount of testing done (at least, it failed tests for a while, and was fixed). It introduces a new test, but could plausibly also use additional tests if @philip-stoev can imagine further cases that would make sense.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

2022-10-26 18:32 UTC, mjibson approved these changes

2022-10-27 11:48 UTC, philip-stoev approved these changes
I tested this manually and also unknowingly came up with the same .td test that you already had ...

That said, we are currently not set up to test the backwards-compatibility of the `response.proto` change as I assume it requires that there is a snapshot in progress while a rolling upgrade is taking place. None of our available upgrade frameworks can deliver that concurrency of events right now.

However, @aalexandrov may have ideas on how to test this as a rust unit test, so I am adding him to this PR.

2022-10-27 12:27 UTC, aalexandrov requested changes
I have some concerns about the backward-compatibility of the evolved `SubscribeBatch`. 

If you think that this is important and might impact existing workloads, let me know and I will propose a fix, otherwise let me know and I will approve this. 

I want to come up with some lightweight methods for asserting that a change is backwards-compatible, so having a real-world playground will be helpful.

2022-10-27 12:27 UTC, aalexandrov commented on src/compute-client/src/response.proto
> -    repeated ProtoUpdate updates = 3;
I don't think this change is not backwards-compatible. A backwards-compatible change will not remove
```
repeated ProtoUpdate updates = 3;
```
but will at first just rename the field name from `updates` to `updates_old`. The `RustType` implementation for `SubscribeUpdates` will then have to populate `self.updates` from `updates_old` or `updates` (currently it only uses the latter).

2022-10-27 12:27 UTC, aalexandrov commented on src/compute-client/src/response.rs
> +            updates: Some(proto_subscribe_batch::ProtoSubscribeBatchContents {
This is not backwards compatible because it won't populate the `updates` field properly from an old version of `ProtoSubscribeBatchContents`.

2022-10-27 13:11 UTC, frankmcsherry commented
So, a few things:
1. I don't think this will impact workloads, as the types are ephemeral at the moment (network connections, rather than cross-version).
2. I'm up for making backward compatible version, but
3. The intent of the PR is to prevent an old `updates` from making it through to `envd` on account of without guards in place it can OOM `envd`. Just copying the pre-existing `updates` over would violate the intent/spirit of that (though, maybe it already OOMd because proto already used all the memory).

Is there general advice for evolution where the requirement is to *remove* a field rather than add one? It's not hard, in this case, to always ignore the old `updates`, but respond to the absence of the new `updates` by introducing an error variant.

2022-10-27 13:48 UTC, aalexandrov commented
> I don't think this will impact workloads, as the types are ephemeral at the moment (network connections, rather than cross-version).

If we are sure that a new version of `environmentd` can never receive a `SubscribeResponse` produced by an older version of `computed` (I refer to this as "assumption A" below), we don't need to worry about backwards compatibility in this PR, and it should be safe to merge as is.

> Is there general advice for evolution where the requirement is to remove a field rather than add one?

I haven't thought about this case so far, as my working assumption was that for backward compatibility there should always a `Proto$Type[vN] ⇒ $Type[vN+1]` embedding, but I get your point.

> It's not hard, in this case, to always ignore the old updates, but respond to the absence of the new updates by introducing an error variant.

I think you are already doing this to some extent:

```rust
fn from_proto(proto: ProtoSubscribeBatch) -> Result<Self, TryFromProtoError> {
    Ok(SubscribeBatch {
        lower: proto.lower.into_rust_if_some("ProtoTailUpdate::lower")?,
        upper: proto.upper.into_rust_if_some("ProtoTailUpdate::upper")?,
        updates: match proto.updates.unwrap().kind {
            // at the moment we will hit this if assumption A is violated
            None => Err(TryFromProtoError::missing_field("ProtoPeekResponse::kind"))?,
        },
    })
}
```

2022-10-27 13:55 UTC, aalexandrov commented
BTW, the `proto.updates.unwrap()` panic from above can also be eliminated:

```rust
fn from_proto(proto: ProtoSubscribeBatch) -> Result<Self, TryFromProtoError> {
    Ok(SubscribeBatch {
        lower: proto.lower.into_rust_if_some("ProtoTailUpdate::lower")?,
        upper: proto.upper.into_rust_if_some("ProtoTailUpdate::upper")?,
        updates: match proto.updates {
            Some(updates) => match updates.kind {
                Some(proto_subscribe_batch::proto_subscribe_batch_contents::Kind::Updates(
                    updates,
                )) => Ok(updates
                    .updates
                    .into_iter()
                    .map(|update| {
                        Ok((
                            update.timestamp.into(),
                            update.row.into_rust_if_some("ProtoUpdate::row")?,
                            update.diff,
                        ))
                    })
                    .collect::<Result<Vec<_>, TryFromProtoError>>()?),
                Some(proto_subscribe_batch::proto_subscribe_batch_contents::Kind::Error(
                    text,
                )) => Err(text),
                None => Err(TryFromProtoError::missing_field("ProtoPeekResponse::kind"))?,
            },
            None => Err(TryFromProtoError::missing_field(
                "ProtoSubscribeBatch::updates",
            ))?,
        },
    })
}
```

In theory `proto.updates.unwrap()` should never panic if it is produced by the same `computed` version, but other parts of the code return an `Err(TryFromProtoError::MissingField)` in that case.

2022-10-27 13:55 UTC, aalexandrov approved these changes

2022-10-27 16:21 UTC, frankmcsherry commented
> I think you are already doing this to some extent:

Ah, I was thinking of something else. Rather than `Err(...)?` it could set `updates: Err("...")` and return without a proto error.

2022-10-27 18:49 UTC, merged