doc: Add Serializable query guarantees to docs
MaterializeInc/materialize pull request #16137
Opened 2022-11-17 18:49 UTC by jkosh44

This commit adds documentation to specify what guarantees we provide in the Serializable isolation level with regards to timestamp selection.

### Motivation
Adds docs

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [X] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - N/A

2022-11-17 18:50 UTC, jkosh44 commented
My writing skills are not great so please be aggressive with suggestions to the language.

2022-11-21 15:57 UTC, morsapaes requested changes
Sorry for the delayed review, @jkosh44! Left a suggestion to rework your original paragraph (as requested 👹).

2022-11-21 15:57 UTC, morsapaes commented on doc/user/content/overview/isolation-level.md
> +these queries will not block and be executed immediately.
```suggestion
If a consistent snapshot is not available across all objects in a query, the query will be blocked until one becomes available. On the other hand, if a consistent snapshot is available, the query will be executed immediately. A consistent snapshot is guaranteed to be available for queries that involve a single object (which includes queries against a single materialized view that was created using multiple objects). Such queries will therefore never block, and always be executed immediately.
```

2022-11-29 13:52 UTC, frankmcsherry reviewed
I think this text is the first in the doc where we say things like "consistent snapshot" and "immediate execution". I'm not opposed to merging the text, but I think we'll also eventually need to explain what these things are.

Might this text make more sense in the "Choosing the right isolation level" section? There we also mention "performance issues" and can be a bit more clear on the essential trade-off (linearizability vs query latency, I think).

2022-11-29 20:43 UTC, merged