not-for-merge: storage: add ability to change wal lag parameters with env vars
MaterializeInc/materialize pull request #16393
Opened 2022-11-30 18:01 UTC by guswynn

for incident 25

2022-11-30 18:05 UTC, petrosagg approved these changes

2022-11-30 18:48 UTC, benesch requested changes
Sorry, I'd rather not rush this in! We've to date had a hard rule about not controlling system behavior with environment variables deep in the guts of the codebase; everything needs to be plumbed in via CLI flags.

2022-11-30 19:27 UTC, guswynn commented
@benesch Ideally this would be controllable from launchdarkly, but we don't have support for that; if we need to alter these variable to investigate this incident, what alternatives do we have?

2022-12-04 17:52 UTC, benesch commented
>  I can plumb these through with cli flags, but it seems quite heavyweight for a single incident, and increases the blast radius of the change

Right, would love to avoid testing in production whenever possible! In absolute emergencies we might have no choice but to rig something up like this, but for relatively isolated incidents that only affect one customer/source, I'd love to avoid rushing in a change like this.

LD will give us more options here, but I wonder if we want to be looking to build something even more targeted: the ability to control these options on a per-PostgreSQL source basis. E.g.:

```
CREATE SOURCE ...
FROM POSTGRES CONNECTION pg (
    MAX WAL LENGTH '2gb'
)
```

Probably don't want to expose those knobs to end users just yet, but we could rig it up so that you can only set them as the `mz_system` user.

2022-12-05 21:41 UTC, guswynn commented
Adjusted to just add logging, as part of the investigation in https://github.com/MaterializeInc/materialize/issues/16484

2022-12-05 21:41 UTC, guswynn commented
@benesch we may end up concluding that this needs to be a user option!

2022-12-05 21:59 UTC, petrosagg approved these changes
The logs look good!

2022-12-05 21:59 UTC, petrosagg commented on src/storage/src/source/postgres.rs
> +                        // mz_storage::source::postgres=debug,info will activate this
leftover comments

2022-12-06 04:20 UTC, benesch approved these changes

2022-12-06 05:00 UTC, merged