[docs] Document more of our intended Kafka semantics
MaterializeInc/materialize pull request #16483
Opened 2022-12-05 21:01 UTC by bkirwi

We'd like to say something useful about our sink semantics. (If we didn't think it was important to avoid duplicates, the sink code would be much simpler!) However, we don't want to commit to more than we can promise, and we don't have much control over either Kafka itself or the specific cluster that MZ is connected to.

This tries to balance the concerns by using Kafka's language for our guarantees (vs. trying to capture Kafka's guarantees in database terminology) and emphasizing the end-to-end nature of an exactly-once processing guarantee and which parts are out of MZ's control.

### Motivation

Followup from an old discussion. Some internal links:
- Slack thread: https://materializeinc.slack.com/archives/C01CFKM1QRF/p1666366042376509
- Internal documentation on the sink design: https://www.notion.so/materialize/Kafka-sink-behaviour-3881b76ed0fe4841a5f549b8aedefd3a

### Tips for reviewer

We didn't really reach a consensus in the above discussion I think; this is just my best attempt to balance the concerns we had at the time. Feel free to push back on or rewrite this if you don't like it! And cc @morsapaes as docs boss.

(Zero rush on this one; just exorcising a few old things from my TODO list.)

2022-12-07 17:50 UTC, morsapaes requested changes
Thanks, @bkirwi! 🙇‍♀️ I've split the sink docs into a core landing page + a Kafka-specific one in #16482, so this would now live under `/create-sink/kafka`. I can push that in!

2022-12-08 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MaterializeInc/materialize?pullRequest=16483) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MaterializeInc/materialize?pullRequest=16483) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MaterializeInc/materialize?pullRequest=16483) it.</sub>

2022-12-08 17:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/MaterializeInc/materialize?pullRequest=16483) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/MaterializeInc/materialize?pullRequest=16483) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/MaterializeInc/materialize?pullRequest=16483) it.</sub>

2022-12-08 19:21 UTC, bkirwi commented
Cool! I'm happpy to redirect this, assuming @frankmcsherry or @umanwizard think this covers the gap we were discussing...

2022-12-13 04:06 UTC, morsapaes approved these changes

2022-12-13 21:48 UTC, bkirwi commented
Thanks - changes look good!

I'll get this in, but I'm happy to come back to it later if anyone else has feelings on it.

2022-12-13 21:49 UTC, merged