doc/user: document mz_dependencies
MaterializeInc/materialize pull request #16936
Opened 2023-01-04 17:37 UTC by guswynn

Documenting: https://github.com/MaterializeInc/materialize/pull/16923

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  - Add mz_internal.mz_dependencies

2023-01-11 00:55 UTC, morsapaes commented on doc/user/content/sql/system-catalog/mz_internal.md
> +The `mz_object_dependencies` table tracks the dependencies between user-created objects.
```suggestion
The `mz_object_dependencies` table describes the dependency structure between objects in the system.
```

2023-01-11 00:57 UTC, morsapaes requested changes
IIRC, you changed the implementation to not filter for user-created objects. Took the chance to make the description consistent with that of `mz_worker_compute_dependencies`.

2023-01-11 07:41 UTC, benesch commented
Applied @morsapaes's code review suggestions and applied a few more of my own: id -> ID, alphabetic sorting, and the blurb about "corresponds to mz_objects.id".

2023-01-12 19:07 UTC, guswynn commented
@morsapaes i believe this is merge-able after the release today!

2023-01-12 19:15 UTC, merged