Replace MIR column runs by ranges
MaterializeInc/materialize pull request #17324
Opened 2023-01-24 21:25 UTC by frankmcsherry

Experiment in which MIR explanations for `MirScalarExpr` sequences that have runs of column references are replaced by `#x .. #y` notation. This as a result of seeing a whole lot of outputs that had 15-long sequences of all the same columns.

### Motivation

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a
  companion cloud PR to account for those changes that is tagged with
  the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):

  -

2023-01-24 22:32 UTC, frankmcsherry commented
Currently failing due to difference of opinion in whether one should produce
```
case when (#3 = 0) then
```
or
```
if (#3 = 0) then
```
probably because some `Display` implementation gets used in one place and not another.

2023-01-25 14:16 UTC, aalexandrov requested changes
As a proof of concept, this looks fine, except some comments on what trait to implement on `MirIndices`.

More generally, I feel like this pattern should be adopted across all IRs (HIR/MIR/LIR) and across all variants that print a sequence of expressions. Let me know if you prefer to do the generalization here or in a follow-up PR.

2023-01-25 14:16 UTC, aalexandrov commented on src/expr/src/explain.rs
> +impl<'a> fmt::Display for MirIndices<'a> {
This should implement `DisplayText` instead.

2023-01-25 14:16 UTC, aalexandrov commented on src/expr/src/explain.rs
> +    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
The signature here should change
```rust
fn fmt_text(&self, f: &mut fmt::Formatter<'_>, ctx: &mut ()) -> fmt::Result {
```
if the enclosing trait is `DisplayText`.

2023-01-25 16:27 UTC, frankmcsherry commented
I pushed a few changes which I think line up with your tips (though, double check because I can't be trusted). I bolted on a `Display` implementation that just uses the `DisplayText` implementation; perhaps that is wrong idk we'll see.

2023-01-26 10:37 UTC, aalexandrov commented
I picked up this PR and opened #17348 for a version that renders compact comma-separated scalar lists across all IRs.

2023-01-30 12:59 UTC, closed without merging