sql: Ensure role member grantor is always valid
MaterializeInc/materialize pull request #18781
Opened 2023-04-15 22:57 UTC by jkosh44

This commit prevents dropping a role, if that role is a grantor fo some
other role membership. This helps ensure that the grantor references in
the catalog always remain valid.
    
As of this commit, the only valid grantor is mz_system which is
impossible to delete. So it's impossible to hit this error scenario.
However, this is more future-proof for when we implement ADMIN OPTION
and allow other grantors.
    
This is based off of the equivalent commit in PostgreSQL here:
https://github.com/postgres/postgres/commit/6566133c5f52771198aca07ed18f84519fac1be7
That commit will be part of PostgreSQL v16 and was not included in v15.
    
Part of #11579

### Motivation
This PR adds a known-desirable feature.

### Checklist

- [X] This PR has adequate test coverage / QA involvement has been duly considered.
- [X] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-04-15 22:58 UTC, jkosh44 commented
This PR builds off of https://github.com/MaterializeInc/materialize/pull/18780. Only the most recent commit is new.

2023-04-17 06:45 UTC, mjibson approved these changes
Last commit LGTM. Probably gotta wait until we decide about the others though.

2023-04-17 16:19 UTC, def- requested changes

2023-04-17 16:26 UTC, jkosh44 commented on src/sql/src/plan/statement/ddl.rs
> +                        let member_role = scx.catalog.get_role(member_id);
It's not possible right now. The only valid role that can be a grantor is `mz_system` which can't be dropped. This is mostly a sanity check as well as future proofing for when we add `ADMIN OPTION`, which will allow other grantors that aren't `mz_system`.

2023-04-17 17:11 UTC, def- approved these changes

2023-04-17 21:51 UTC, merged