ci: Test output consistency between constant-folding vs. rendered query evaluations
MaterializeInc/materialize pull request #18812
Opened 2023-04-18 06:59 UTC by nrainer-materialize

TODO:
* validate results
* create issues where necessary and link them

2023-04-18 07:03 UTC, nrainer-materialize commented on test/sqllogictest/transform/fold_constants.slt
> +
Shall I move the following code to separate files to reduce the length of this one?

2023-04-18 07:03 UTC, nrainer-materialize commented on test/sqllogictest/transform/fold_constants.slt
> +# 5) repeat row (=> this panics!)
This panics and lets the test crash. How to proceed here?
https://github.com/MaterializeInc/materialize/issues/17758#issuecomment-1438824467 mentions that it requires requires `--unsafe-mode`.

2023-04-18 07:18 UTC, nrainer-materialize commented
> @nrainer-materialize did you write those queries by hand or you used a script to generate them?

Queries are handwritten, results are generated.

2023-04-18 08:59 UTC, nrainer-materialize commented on test/sqllogictest/transform/fold_constants.slt
> +
=> I split them by computation mode (to allow easier comparisons) and content (to reduce the file length).

2023-04-18 09:40 UTC, def- requested changes
> [2023-04-18T08:59:54Z] lint: error: copyright: test/sqllogictest/transform/fold_vs_dataflow/1_numbers_dataflow.slt is missing copyright header

You can copy the copyright header from another file

2023-04-18 10:55 UTC, vmarcos reviewed
Thanks for working on these tests! Not sure how much time you are willing to invest into refining these, but here are a few more items that would be good to validate:

- Top-K computation, both with LATERAL JOIN (i.e., with groups) or not.
- More coverage of set operations, e.g., `EXCEPT`, `EXCEPT ALL`.
- More coverage of joins.
- If possible, filters.

The constant-folding transformation has arms to handle all of the above: https://github.com/MaterializeInc/materialize/blob/8147c0b1a6a4b6d0c318f947a23ca4c57ad47142/src/transform/src/fold_constants.rs#L85-L402.

A complementary approach to having a fixed test suite that runs as part as our fast SQL logic tests is to also include a set of constant relations (created as views the way you do in the tests in this PR) in our fuzzing nightlies with SQLsmith. Would this be feasible?

2023-04-18 10:55 UTC, vmarcos commented on test/sqllogictest/transform/fold_vs_dataflow/3_number_aggfns_dataflow.slt
> + AVG(real1 + real1), AVG(double1 + double1), AVG(numeric1 + numeric1)
Should we have expressions here also with the integer columns?

2023-04-18 10:55 UTC, vmarcos commented on test/sqllogictest/transform/fold_vs_dataflow/5_repeat_row_dataflow.slt
> +# 2023-04-18T09:50:00.705649Z  WARN mz_storage_client::controller::rehydration: storage cluster produced error, reconnecting: status: Unknown, message: "error reading a body from connection: broken p
This looks like an instance of https://github.com/MaterializeInc/materialize/issues/18738. The panic should disappear in `release` mode and instead manifest as a wrap-around.

2023-04-18 11:42 UTC, def- commented
> A complementary approach to having a fixed test suite that runs as part as our fast SQL logic tests is to also include a set of constant relations (created as views the way you do in the tests in this PR) in our fuzzing nightlies with SQLsmith. Would this be feasible?

SQLsmith might be difficult. I think a new oracle for SQLancer would be possible, but some effort and probably on my plate.

2023-04-18 11:43 UTC, philip-stoev approved these changes
I would defer to @vmarcos so say if more testing is needed as part of this task -- if this is the case, I think some sort of scripting should be used in order to exercise the various combinations more exhaustively.

2023-04-18 12:19 UTC, vmarcos commented
> I would defer to @vmarcos so say if more testing is needed as part of this task -- if this is the case, I think some sort of scripting should be used in order to exercise the various combinations more exhaustively.

I think that to uncover potential new issues, a scripting approach would be ideal, yes. That way, we'd get more coverage of the constant-folding code, increasing confidence. This PR, however, already improves on our current state of affairs. So would you be OK with saying this PR advances https://github.com/MaterializeInc/materialize/issues/17767, but does not close it? That way, we can take on follow-up work separately and merge this now.

2023-04-18 14:19 UTC, nrainer-materialize commented
> I would defer to @vmarcos so say if more testing is needed as part of this task -- if this is the case, I think some sort of scripting should be used in order to exercise the various combinations more exhaustively.

I took the time to briefly sketched a [small Python script to generate such code](https://github.com/nrainer-materialize/materialize/commit/290ba10cadc5114f475147660e252edf5146b3cd) for mathematical operations. An excerpt of the output is:
```

# -------------------------------
# BEGIN TYPE UINT2 USING VIEW (constant folding)
# -------------------------------

statement ok
CREATE VIEW v_data_UINT2 (zero_value, max_value, smallest_value) AS SELECT 0::UINT2, 65535::UINT2, 1::UINT2, 1::UINT2;

query III
SELECT SUM(max_value), MIN(max_value), MAX(max_value) FROM v_data_UINT2;
----
<to be generated with --write-results>

query III
SELECT SUM(max_value + max_value), MIN(max_value + max_value), MAX(max_value + max_value) FROM v_data_UINT2;
----
<to be generated with --write-results>
```

@philip-stoev: Is this something I should proceed with or would you like me to continue on other issues with higher priorities?

2023-04-19 09:26 UTC, def- approved these changes

2023-04-19 09:31 UTC, vmarcos approved these changes
Sounds good to me! It would be great also if you would either create another issue for the follow-up work or not close the original one, whichever you prefer.

2023-04-20 07:14 UTC, nrainer-materialize commented
> Sounds good to me! It would be great also if you would either create another issue for the follow-up work or not close the original one, whichever you prefer.

To be addressed with https://github.com/MaterializeInc/materialize/issues/18858.

2023-04-20 07:15 UTC, merged