add overview updates
MaterializeInc/materialize pull request #18839
Opened 2023-04-19 13:17 UTC by tr0njavolta

2023-04-24 12:08 UTC, morsapaes reviewed
Reviewing this in chunks: `isolation-level.md`

2023-04-24 18:01 UTC, morsapaes requested changes

2023-04-24 18:04 UTC, morsapaes commented
In general, we should make sure this page aligns with the descriptions proposed by Jesse in the new get started guide. There's also some descriptions that can be lifted from the object-specific `CREATE` pages or the mentioned blogposts, to make sure we cover important details that are currently left out.

2023-04-24 21:43 UTC, jseldess commented on doc/user/content/overview/key-concepts.md
> +Most physical and cloud-hosted database solutions require you to configure
I think we need to more directly introduce the purpose of this page, and not focus on the benefits of a managed service in general. Suggestion (to start from):

```suggestion
This page introduces the key objects of Materialize.  
```

We might want to also say something like:

```
Some of these objects correspond traditional SQL idioms but have different properties and behaviors in the context of a streaming database like Materialize.
```

2023-04-25 10:15 UTC, jseldess requested changes
I agree with Marta's comments and left some of mine own. I appreciate all the time and effort put into this already, but given how much we lean on this page, we need to spend more time on this.

2023-04-25 10:15 UTC, jseldess commented on doc/user/content/overview/key-concepts.md
>  #### Connectors
I agree. If we take the "Getting data in" approach, we could intro with something like this (lifted and extended from my getting started draft):

> Materialize supports streaming data from multiple external sources, including [Kafka](/sql/create-source/kafka/) and [PostgreSQL](/sql/create-source/postgres/). The process for integrating a source involves working with three Materialize concepts: secrets, connections, and sources.

2023-04-25 10:15 UTC, jseldess commented on doc/user/content/overview/key-concepts.md
> +**Materialized views** | Query results stored durably.
Agreed.

2023-04-25 15:17 UTC, tr0njavolta commented
Closing pr draft to pull back on key-concepts doc as it needs more time to revise.

2023-04-25 15:17 UTC, closed without merging