dbt-materialize: Additional 1.5 Tests
MaterializeInc/materialize pull request #19115
Opened 2023-05-04 17:36 UTC by dehume

### Motivation

New tests for the dbt adapter tests included with the [dbt-core 1.5.0 release](https://github.com/MaterializeInc/materialize/issues/18843). Including tests for incrementals but setting pytest to skip.

### Tips for reviewer

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-05-08 10:59 UTC, morsapaes requested changes
From a quick check, it seems like there's a couple more tests we should cover, like [`/hooks`](https://github.com/dbt-labs/dbt-core/tree/main/tests/adapter/dbt/tests/adapter/hooks). If we're including `test_snapshot` and `test_incremental` (both unsupported features), it'd make sense to also include [`test_persist_docs`](https://github.com/dbt-labs/dbt-core/tree/main/tests/adapter/dbt/tests/adapter/persist_docs) (pointing to #17216).

2023-05-08 10:59 UTC, morsapaes commented on misc/dbt-materialize/setup.py
> +    version="1.5.0",
We don't want to bump the version just yet, in order to not trigger a release (see [PyPI release step](https://github.com/MaterializeInc/materialize/blob/c1938366ddf784fabe229817420c1b88ceffaf14/ci/deploy/pypi.py#L37-L47)).

2023-05-09 16:58 UTC, dehume commented
Included additional tests (such as hooks). Was not able to a persist doc tests because Materialize currently does not support comments (so included the tests but set to skip).

2023-05-10 23:30 UTC, morsapaes approved these changes

2023-05-11 10:09 UTC, merged