Update mz_internal.mz_cluster_replica_history
MaterializeInc/materialize pull request #19300
Opened 2023-05-15 20:18 UTC by umanwizard

Fixes two issues with this view.

First, we were surfacing an "old-style" replica ID, which is an implementation detail of `mz_audit_events`. To get the corresponding publicly-relevant "new-style" replica ID, we now prepend it with "u".

Second, we need to include `replica_name` and `cluster_name` in this view, since in general users won't be able to get those by joining against `mz_clusters` and `mz_cluster_replicas`, in the case where the cluster or replica has already been dropped.

See full discussion [here](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1684175174531589).

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] This PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way) and therefore is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Improve the relevance of the information in `mz_cluster_replica_history`.

2023-05-15 20:19 UTC, benesch requested changes
Just requesting a hold on this PR while I get my bearings; I think we should maybe write a migration for `mz_audit_events` that fixes the IDs; thoughts incoming on Slack.

2023-05-15 21:04 UTC, benesch commented on src/adapter/src/catalog/builtin.rs
> +            'u' || creates.replica_id AS replica_id,
@umanwizard and I discussed live that this view should just pass the `replica_id` straight through, and we'll solve the ID migration issue independently of this PR.

2023-05-16 03:03 UTC, umanwizard commented
Left in the ID from `mz_audit_events`, but renamed it to `internal_replica_id` to make it clear that it doesn't correspond to other notions of replica ID. We can rename this column after we do the migration.

2023-05-16 03:49 UTC, benesch approved these changes

2023-05-16 04:35 UTC, merged