SLT: Check mz_arrangement_sharing at the end of each file
MaterializeInc/materialize pull request #20180
Opened 2023-06-27 09:58 UTC by def-

Fixes: #20179

### Motivation

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-06-28 07:26 UTC, philip-stoev requested changes
I am afraid changing that many files to add a single query is not a sustainable way to do things.

Here is what I would suggest:
- extend testdrive to allow for a follow-up .td file to run after each .td file specified on the command line.
- extend test/testdrive/mzcompose.py to pass such an option to testdrive by default.

2023-06-28 11:15 UTC, vmarcos reviewed
This looks good overall, but there are a few arrangements that we do not cover yet. One issue is related to feature flags (see below). I will add a few comments regarding introspection arrangements too. In addition, I had some trouble getting a few to manifest ([Slack thread](https://materializeinc.slack.com/archives/C02PPB50ZHS/p1687950924858099)).

2023-06-28 11:16 UTC, vmarcos commented
In the `mz_introspection` cluster, we run a number of dataflows. Here's a simple check that we'd probably like to have as additions to `testdrive` test focused on `mz_arrangement_sharing`:

```sql
materialize=> set cluster to mz_introspection;
SET
Time: 3.196 ms
materialize=> SELECT mdo.name FROM mz_internal.mz_arrangement_sharing mash JOIN mz_internal.mz_dataflow_operators mdo ON mash.operator_id = mdo.id ORDER BY mdo.name;
                              name                              
----------------------------------------------------------------
 AccumulableErrorCheck
 ArrangeAccumulable
 ArrangeBy[[Column(0), Column(1), Column(2), Column(3)]]
 ArrangeBy[[Column(0), Column(1), Column(2), Column(3)]]-errors
 ArrangeBy[[Column(0), Column(2)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(0)]]-errors
 ArrangeBy[[Column(1), Column(0)]]
 ArrangeBy[[Column(1), Column(3)]]
 ArrangeBy[[Column(1), Column(3)]]
 ArrangeBy[[Column(1)]]
 ArrangeBy[[Column(1)]]
 ArrangeBy[[Column(1)]]
 ArrangeBy[[Column(1)]]-errors
 ArrangeBy[[Column(1)]]-errors
 ArrangeBy[[Column(2), Column(3)]]
 ArrangeBy[[Column(2), Column(3)]]-errors
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(2)]]-errors
 ArrangeBy[[Column(3)]]
 ArrangeBy[[Column(4), Column(5), Column(6)]]
 ArrangeBy[[Column(4), Column(5), Column(6)]]-errors
 Arranged DistinctBy
 Arranged ReduceInaccumulable
 Arranged TopK input
 Arranged TopK input
 Arranged TopK input
 Arranged TopK input
 Arranged TopK input
 Arranged TopK input
 Arranged TopK input
 Arranged TopK input
 DistinctBy
 DistinctByErrorCheck
 JoinStage
 JoinStage
 ReduceAccumulable
 ReduceInaccumulable
 ReduceInaccumulable Error Check
 Reduced TopK input
 Reduced TopK input
 Reduced TopK input
 Reduced TopK input
 Reduced TopK input
 Reduced TopK input
 Reduced TopK input
 Reduced TopK input
(94 rows)

Time: 30.205 ms
```

2023-06-28 11:17 UTC, vmarcos commented
We can also check the dataflows that are part of our logging infrastructure if we enable `log_logging`. This can be done as follows:

```sql
materialize=> CREATE CLUSTER REPLICA default.r2 SIZE = '2', INTROSPECTION DEBUGGING = true;
CREATE CLUSTER REPLICA
Time: 195.478 ms
materialize=> SET cluster_replica = r2;
SET
Time: 0.941 ms
materialize=> SELECT mdo.name FROM mz_internal.mz_arrangement_sharing mash JOIN mz_internal.mz_dataflow_operators mdo ON mash.operator_id = mdo.id ORDER BY mdo.name;
                     name                      
-----------------------------------------------
 Arrange Timely(Reachability)
 ArrangeByKey Compute(DataflowCurrent)
 ArrangeByKey Compute(DataflowDependency)
 ArrangeByKey Compute(FrontierCurrent)
 ArrangeByKey Compute(FrontierDelay)
 ArrangeByKey Compute(ImportFrontierCurrent)
 ArrangeByKey Compute(PeekCurrent)
 ArrangeByKey Compute(PeekDuration)
 ArrangeByKey Differential(ArrangementBatches)
 ArrangeByKey Differential(ArrangementRecords)
 ArrangeByKey Differential(Sharing)
 ArrangeByKey Timely(Addresses)
 ArrangeByKey Timely(Channels)
 ArrangeByKey Timely(Elapsed)
 ArrangeByKey Timely(Histogram)
 ArrangeByKey Timely(MessagesReceived)
 ArrangeByKey Timely(MessagesSent)
 ArrangeByKey Timely(Operates)
 ArrangeByKey Timely(Parks)
(19 rows)

Time: 25.098 ms
```

2023-07-04 21:02 UTC, def- commented
> extend testdrive to allow for a follow-up .td file to run after each .td file specified on the command line.

@philip-stoev Would it really be fine to have an additional `.followup.td` for so many td files? If so, I can implement it.

My idea would have been to select a few interesting views and put them in the dedicated td file to check the mz_arrangement_sharing.

2023-07-15 06:56 UTC, philip-stoev approved these changes

2023-07-15 09:03 UTC, merged