stash: ensure objects and latest version protos have matching hashes
MaterializeInc/materialize pull request #20956
Opened 2023-08-02 22:41 UTC by guswynn

I noticed there is nothing ensuring the objects hash matches the latest versioned files hash. This is because it has a different package name. This pr edits the file in memory to ensure the hashes match.

It also asserts this equivalence, and maintains the order of the hashes file.

### Motivation

   * This PR refactors existing code.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-08-03 14:03 UTC, ParkMyCar requested changes
Adding a strict ordering to the `hashes.json` list is great! We already have a [test](https://github.com/ParkMyCar/materialize/blob/main/src/stash/src/objects.rs#L309) that asserts the latest snapshot is the same as the current objects. Did you experience this test not working though?

2023-08-04 16:05 UTC, guswynn commented
@ParkMyCar this prevents people from making mistakes in the "edit-`cargo check`-`cargo build`" loop. I don't think I ended up running that test except in ci

2023-08-08 13:51 UTC, ParkMyCar approved these changes
Ahh good point! Could you just leave a comment somewhere that the hashes are an MD5 of file, but with the package name changed? You could probably deduce that from the code, but calling it out somewhere explicitly would be nice

2023-08-08 13:51 UTC, ParkMyCar commented
@guswynn thanks for making this improvement! 😊

2023-08-10 17:58 UTC, guswynn commented
yes ill add a comment! also need to rebase this!

2023-08-10 19:24 UTC, merged

2023-08-10 19:54 UTC, mjibson commented
This change broke cargo check caching, so now this crate must be rechecked always.