mz: update README.md + MAINTAINERS.md + CHANGELOG.md
MaterializeInc/materialize pull request #21251
Opened 2023-08-18 12:33 UTC by joacoc

### Motivation

This PR adds missing documents for `mz`:
- `README.md`
- `CHANGELOG.md`

It also includes a subtle fix to `MAINTAINERS.md`.

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-08-21 13:24 UTC, morsapaes commented on src/mz/MAINTAINERS.md
> +4. Open a PR with your change and get it merged:
Looks like you missed the one below (5.)!

2023-08-21 13:24 UTC, morsapaes approved these changes

2023-08-21 16:46 UTC, morsapaes requested changes

2023-08-21 16:46 UTC, morsapaes commented on src/mz/README.md
> +## Dependencies
These dependencies are for local development...right? It's confusing to list them here.

2023-08-22 10:21 UTC, joacoc commented on src/mz/CHANGELOG.md
> +This new version contains a big revamp of the `mz` CLI. It includes updated code with an entirely different pattern for `profiles`.
Is it a refactor if it implies external effects?

2023-08-22 10:26 UTC, joacoc commented on src/mz/MAINTAINERS.md
>  ## Cutting a new release
I was planning to set the `1.0` before making it public to users (after the private test internally.) Does it makes sense?

2023-08-22 10:32 UTC, joacoc commented on src/mz/README.md
> +   [`mz region enable`](reference/region) to enable one.
Mhh. Interesting. This error is new. You should be able to enable a region that is already enabled. In anycase, it doesn't have any positive impact for the customer and can take down `environmentd` for a few minutes. So the best thing will be to just say it is not possible to do, and only enable it for internal  devs with a flag.

2023-08-22 10:33 UTC, joacoc commented on src/mz/README.md
> +   curl -fsSL https://dev.materialize.com/apt/materialize.sources | sudo tee /etc/apt/sources.list.d/materialize.sources
Issue created: https://github.com/MaterializeInc/materialize/issues/21321

2023-08-22 10:38 UTC, joacoc commented on src/mz/README.md
> +   [`mz region enable`](reference/region) to enable one.
Issue created: https://github.com/MaterializeInc/materialize/issues/21322

2023-08-22 11:09 UTC, joacoc commented on src/mz/README.md
> +   mz profile init
Issue created: https://github.com/MaterializeInc/materialize/issues/21326

2023-08-22 11:15 UTC, joacoc commented on src/mz/README.md
> +    user            Manage users in your organization
Issue created: https://github.com/MaterializeInc/materialize/issues/21327

2023-08-23 12:10 UTC, morsapaes commented on src/mz/CHANGELOG.md
> +This new version contains a big revamp of the `mz` CLI. It includes updated code with an entirely different pattern for `profiles`.
That's a good point, I commented before noticing that this also introduces new functionality. Edited the suggestion!

2023-08-23 12:11 UTC, morsapaes approved these changes

2023-08-23 14:33 UTC, merged

2023-08-29 12:19 UTC, joacoc commented on src/mz/README.md
> +   curl -fsSL https://dev.materialize.com/apt/materialize.sources | sudo tee /etc/apt/sources.list.d/materialize.sources
@morsapaes can I ask you which Linux dist are you using?