Docs 19122 msk guide updates
MaterializeInc/materialize pull request #21504
Opened 2023-08-31 15:52 UTC by bobbyiliev

### Motivation

Refreshing the Kafka MSK and self-managed Kafka guides to provide end-to-end and correct guidance per the issue described [here](https://github.com/MaterializeInc/materialize/issues/19374).

Also, separating the Privatelink and SSH network security guides into separate reusable components in order to prevent content duplication as those instructions are re-used in a lot of separate guides.

2023-09-10 14:23 UTC, morsapaes requested changes
Thank you, Bobby! Made a bunch of purely formatting-related suggestions, so that everything is consistent (also with the PostgreSQL integrations guides).

2023-09-10 14:23 UTC, morsapaes commented on doc/user/layouts/shortcodes/network-security/ssh-host.md
> +   return two public keys:
```suggestion
1. Materialize stores public keys for SSH tunnels in the system catalog. Query [`mz_ssh_tunnel_connections`](/sql/system-catalog/mz_catalog/#mz_ssh_tunnel_connections) to retrieve the public keys:
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/layouts/shortcodes/network-security/ssh-host.md
> +In Materialize, use a `CREATE CONNECTION` statement to create an [SSH tunnel connection](/sql/create-connection/#ssh-tunnel) to the bastion server:
```suggestion
In Materialize, create an [SSH tunnel connection](/sql/create-connection/#ssh-tunnel) to the bastion host:
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/layouts/shortcodes/network-security/ssh-host.md
> +## Configure the SSH bastion server
```suggestion
## Configure the SSH bastion host
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/layouts/shortcodes/network-security/ssh-host.md
> +4. Verify the tunnel connection from your source to your SSH bastion host
```suggestion
4. Verify the SSH tunnel connection from your source to your bastion host:
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/layouts/shortcodes/network-security/ssh-host.md
> +    Verify that you can connect to the Kafka broker or PostgreSQL instance via the tunnel:
```suggestion
    Verify that you can connect to the Kafka broker or PostgreSQL instance via the SSH tunnel:
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/layouts/shortcodes/network-security/ssh-host.md
> +5. Retrieve the static egress IPs from Materialize and configure the firewall rules (e.g. AWS Security Groups) for your SSH bastion to allow SSH traffic for those IP addresses only.
```suggestion
5. Retrieve the static egress IPs from Materialize and configure the firewall rules (e.g. AWS Security Groups) for your bastion host to allow SSH traffic for those IP addresses only.
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/layouts/shortcodes/network-security/ssh-host.md
> +Materialize can connect to data sources like Kafka, Confluent, and PostgreSQL with a
Nit: could you rename the shortcode to be `ssh-tunnel`?

2023-09-10 14:23 UTC, morsapaes commented on doc/user/content/ingest-data/kafka-self-hosted.md
> +title: "Self-hosted Kafka"
```suggestion
title: "Ingest data from Self-hosted Kafka"
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/content/ingest-data/kafka-self-hosted.md
> +    name: "Self-hosted Kafka"
```suggestion
    name: "Self-hosted"
```

2023-09-10 14:23 UTC, morsapaes commented on doc/user/content/ingest-data/network-security/privatelink.md
> +- [AWS Kafka integration guide](/integrations/aws-kafka)
```suggestion
- Integration guides: [Self-hosted PostgreSQL](/ingest-data/postgres-self-hosted), [Amazon RDS for PostgreSQL](/ingest-data/postgres-amazon-rds), [Self-hosted Kafka](/ingest-data/kafka-self-hosted), [Amazon MSK](/ingest-data/amazon-msk)
```

2023-09-11 15:03 UTC, dehume approved these changes

2023-10-12 16:59 UTC, morsapaes approved these changes

2023-10-12 17:01 UTC, merged