fix and re-enable statement_logging.py check
MaterializeInc/materialize pull request #22624
Opened 2023-10-24 16:20 UTC by umanwizard

The statement log can lose updates across versions, which was causing the check to expectedly fail.

### Motivation

  * This PR fixes #22448 

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - None

2023-10-25 07:06 UTC, philip-stoev approved these changes

2023-10-25 07:24 UTC, def- approved these changes

2023-10-25 09:14 UTC, def- requested changes
I ran nightly against this change, still fails: https://buildkite.com/materialize/nightlies/builds/4862#018b65c3-fd17-4d5f-9156-a5e13d356840
```
> SELECT count(*) <= 2 FROM mz_internal.mz_statement_execution_history mseh, mz_internal.mz_prepared_statement_history mpsh WHERE mseh.prepared_statement_id = mpsh.id AND sql LIKE '%/* Btv was here */' ORDER BY mseh.began_at;
rows didn't match; sleeping to see if dataflow catches up 50ms 75ms 113ms 169ms 253ms 380ms 570ms 854ms 1s 2s 3s 4s 6s 10s 15s 22s 33s 49s 74s 78s
^^^ +++
4:1: error: preparing query failed: db error: ERROR: column "mseh.began_at" must appear in the GROUP BY clause or be used in an aggregate function: ERROR: column "mseh.began_at" must appear in the GROUP BY clause or be used in an aggregate function
     |
   2 | $ postgres-execute c ... [rest of line truncated for security]
   3 | ALTER SYSTEM SET enable_rbac_checks TO false
   4 | > SELECT count(*) <= 2 FROM mz_internal.mz_statement_execution_history mseh, mz_internal.mz_prepared_statement_history mpsh WHERE mseh.prepared_statement_id = mpsh.id AND sql LIKE '%/* Btv was here */' ORDER BY mseh.began_at;
     | ^
```

2023-10-25 22:57 UTC, def- approved these changes
Thanks, nightly looks good now

2023-10-26 06:57 UTC, nrainer-materialize approved these changes
Thank you!

2023-10-26 13:25 UTC, def- approved these changes

2023-10-26 14:08 UTC, merged