[process orchestrator] Use systemd if available
MaterializeInc/materialize pull request #22702
Opened 2023-10-26 16:18 UTC by antiguru

This PR uses systemd-run if available to limit the CPU and memory resources a process can consume. It detects at runtime if systemd is available, and defaults to the current behavior if it's not.

Also adjusts the replica size definitions to include a CPU limit, and introduce some variants with explicit memory limits. We could align this to be closer to what we use in production.

  * This PR adds a feature that has not yet been specified.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-10-26 18:47 UTC, jkosh44 approved these changes
I know nothing about systemd, but the code LGTM

2023-10-26 18:47 UTC, jkosh44 commented on src/adapter/src/catalog/config.rs
Every time I see this function I'm a bit scared that the `default` method should never be called in production. I supposed that's not exactly relevant to this PR though.

2023-10-27 09:53 UTC, nrainer-materialize commented
I triggered a [nightly build](https://buildkite.com/materialize/nightlies/builds/4913#). Results look good (the platform checks are fixed on main with https://github.com/MaterializeInc/materialize/pull/22719; the postgres-inconsistency is unrelated, I will take care of that).

2023-10-27 16:01 UTC, vmarcos requested changes
This looks fine to me overall, but perhaps we'd like to abstract the formula to compute `workers -> CpuLimit` only once instead of writing it a few times. If I did not misread something, there might be one constant that needs fixing below?

2023-10-27 18:00 UTC, antiguru commented on src/adapter/src/catalog/config.rs
> +                    cpu_limit: Some(CpuLimit::from_millicpus(2000)),
Yup, makes sense! Added and fixed.

2023-10-27 18:00 UTC, antiguru commented on src/adapter/src/catalog/config.rs
> +                    (format!("{workers}-8G"), Some(8)),
Good idea; done.

2023-10-27 18:04 UTC, antiguru commented on src/adapter/src/catalog/config.rs
Filed #22747 so we're less likely to forget. I've been thinking the same!

2023-10-30 09:23 UTC, vmarcos approved these changes
Nice, thank you!

2023-10-31 18:46 UTC, merged