scalability framework: introduce data-frame abstraction layer
MaterializeInc/materialize pull request #23060
Opened 2023-11-09 09:40 UTC by nrainer-materialize

This should make handling data frames more robust and is the base for the boxplot fix.

2023-11-09 09:54 UTC, philip-stoev requested changes
I sense a new startup idea here :-)

On a more serious note, can you put ```""" . """``` style comments for all the new classes?

2023-11-09 10:10 UTC, def- approved these changes

2023-11-09 17:02 UTC, nrainer-materialize commented
> On a more serious note, can you put `""" . """` style comments for all the new classes?

Added with https://github.com/MaterializeInc/materialize/pull/23060/commits/956f7e8e8c1bdcded3315b25e82821e4d1608f5f.

2023-11-10 10:49 UTC, philip-stoev approved these changes

2023-11-10 10:50 UTC, merged