test: Disable shadow catalog in parallel tests
MaterializeInc/materialize pull request #23167
Opened 2023-11-13 21:56 UTC by jkosh44

The Shadow catalog does the following on every catalog operation:

    1. Execute the operation on catalog A.
    2. Execute the operation on catalog B.
    3. Compare the results.

The parallel-workload tests will randomly kill Materialize, so we could end up in a situation where the operation happens on catalog A but not on catalog B, and we will see an inconsistency between the two catalogs. The shadow catalog is meant to be used to compare two catalog implementations, so it's OK that it has this deficiency. Given that, this commit disables the shadow catalog in parallel-workload tests.

Fixes #23146

### Motivation

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-11-13 22:56 UTC, def- requested changes
We only kill materialized randomly in the KillScenario. Would it make sense to keep it for the other scenarios? Probably needs a Materialized-override then for the c.up in line 68 based on the value of `args.scenario == Scenario.Kill`.

2023-11-13 23:03 UTC, jkosh44 commented
> We only kill materialized randomly in the KillScenario. Would it make sense to keep it for the other scenarios? Probably needs a Materialized-override then for the c.up in line 68 based on the value of `args.scenario == Scenario.Kill`.

If possible then yes, it would make sense, however I have no idea how the parallel tests work. The one constraint is that once Materialize boots up with one catalog store, it must use always use the same catalog store.

2023-11-13 23:09 UTC, def- commented
I'll push into your branch.

2023-11-13 23:14 UTC, def- commented
I'm afraid there might be more tests with this problem, let's see:
```
balancerd/mzcompose.py:    c.kill("materialized")
balancerd/mzcompose.py:    c.kill("materialized")
cluster/mzcompose.py:    c.kill("materialized")
cluster/mzcompose.py:        c.kill("materialized")
cluster/mzcompose.py:        c.kill("materialized")
cluster/mzcompose.py:        c.kill("materialized")
cluster/mzcompose.py:        c.kill("materialized")
cluster/mzcompose.py:        c.kill("materialized")
cluster/mzcompose.py:    c.kill("materialized")
cluster/mzcompose.py:    c.kill("materialized")
cluster/mzcompose.py:    c.kill("materialized")
incident-72/mzcompose.py:        c.kill("materialized")
incident-72/mzcompose.py:    c.kill("materialized")
incident-72/mzcompose.py:        c.kill("materialized")
kafka-exactly-once/mzcompose.py:    c.kill("materialized")
kafka-ingest-open-loop/mzcompose.py:    c.kill("materialized")
legacy-upgrade/mzcompose.py:    c.kill("materialized")
legacy-upgrade/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:    c.kill("materialized")
persistence/mzcompose.py:        c.kill("materialized")
pg-cdc-resumption/mzcompose.py:    c.kill("materialized")
replica-isolation/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
restart/mzcompose.py:    c.kill("materialized")
ssh-connection/mzcompose.py:    c.kill("materialized")
upsert/mzcompose.py:            c.kill("materialized")
upsert/mzcompose.py:            c.kill("materialized")
```

2023-11-14 00:02 UTC, def- commented
I'm pretty confused as to why I'm getting new errors in kill scenario now with stash catalog: https://buildkite.com/materialize/nightlies/builds/5180#018bcb17-434b-4cd9-a971-baa246182f32
Did something change? Haven't seen those before, otherwise I'll investigate on Wednesday (I'm out on Tuesday)

2023-11-14 18:18 UTC, jkosh44 commented
> I'm pretty confused as to why I'm getting new errors in kill scenario now with stash catalog: https://buildkite.com/materialize/nightlies/builds/5180#018bcb17-434b-4cd9-a971-baa246182f32 Did something change? Haven't seen those before, otherwise I'll investigate on Wednesday (I'm out on Tuesday)

I don't think anything changed. What is the error? I'm having a hard time finding it in the test output. Is it this?

```
Exception in thread worker_30:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/parallel_workload/worker.py", line 87, in run
    ReconnectAction(self.rng, self.composition, random_role=False).run(
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/parallel_workload/action.py", line 903, in run
    autocommit = exe.cur._c.autocommit
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'autocommit'
Exception in thread worker_31:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/parallel_workload/worker.py", line 87, in run
    ReconnectAction(self.rng, self.composition, random_role=False).run(
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/parallel_workload/action.py", line 903, in run
    autocommit = exe.cur._c.autocommit
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'autocommit'
Exception in thread worker_21:
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/parallel_workload/worker.py", line 87, in run
    ReconnectAction(self.rng, self.composition, random_role=False).run(
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/parallel_workload/action.py", line 903, in run
    autocommit = exe.cur._c.autocommit
                 ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'autocommit'
QPS: 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.1 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.0 000.1 000.1 000.0
mzcompose: test case workflow-default failed: <class 'Exception'>: Thread worker_21 failed, exiting
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/mzcompose/composition.py", line 470, in test_case
    yield
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/cli/mzcompose.py", line 591, in handle_composition
    composition.workflow(args.workflow, *args.unknown_subargs[1:])
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/mzcompose/composition.py", line 360, in workflow
    func(self, parser)
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/test/parallel-workload/mzcompose.py", line 94, in workflow_default
    run(
  File "/var/lib/buildkite-agent/builds/buildkite-builders-d43b1b5-i-0cf3b7dfef0a2803e-1/materialize/nightlies/misc/python/materialize/parallel_workload/parallel_workload.py", line 274, in run
    raise Exception(f"Thread {thread.name} failed, exiting")
Exception: Thread worker_21 failed, exiting
--- Uploading report for suite 'mzcompose' to Buildkite Test Analytics
202 {"id":"8e5670ea-55d0-490d-b810-2b15604248bb","run_id":"c5daa355-148b-4ec1-877d-fc1b964aeb00","queued":1,"skipped":0,"errors":[],"run_url":"https://buildkite.com/organizations/materialize/analytics/suites/mzcompose/runs/c5daa355-148b-4ec1-877d-fc1b964aeb00"}
mzcompose: error: at least one test case failed
```

If so, that looks like an issue in python interacting with the PostgreSQL python library, and not something related to the catalog.

2023-11-15 08:12 UTC, philip-stoev submitted a review, later dismissed
The left == right assertion also happens in Platform Checks backup + restore, the diff there is in one timestamp value. I think all of the platform checks need to be switched to the safe implementation, as almost all of them will kill Mz at some point or another.

2023-11-15 10:07 UTC, def- approved these changes
Nightly looks good now: https://buildkite.com/materialize/nightlies/builds/5215
Can be submitted imo (but I now wrote the code,so will wait for another review.

2023-11-15 10:14 UTC, nrainer-materialize approved these changes
Fine with me if nightly is happy.

2023-11-15 12:02 UTC, def- commented
This decreases nightly flakiness. Hopefully we have all the interesting tests excluded now.

2023-11-15 12:03 UTC, merged

2023-11-15 14:15 UTC, jkosh44 commented
> The left == right assertion also happens in Platform Checks backup + restore, the diff there is in one timestamp value. I think all of the platform checks need to be switched to the safe implementation, as almost all of them will kill Mz at some point or another.

This just made me realize that any test that shuts down Materialize and then brings it back up has the chance to flake due to timestamps. Even an idle Materialize will update the timestamps every 10 seconds. If we happen to restart in the middle of that a timestamp update, it's possible that only one of the catalog gets updated. Are there other tests where we do that?

2023-11-15 14:32 UTC, def- commented
Nearly every test does that. Could we change the assertion not to compare timestamps for that but everything else?

2023-11-15 14:34 UTC, jkosh44 commented
> Nearly every test does that. Could we change the assertion not to compare timestamps for that but everything else?

Yeah, I'll put something together today.

2023-11-15 15:48 UTC, jkosh44 commented
> > Nearly every test does that. Could we change the assertion not to compare timestamps for that but everything else?
> 
> Yeah, I'll put something together today.

https://github.com/MaterializeInc/materialize/pull/23219