slt: No --auto-index-selects for pretty_sql
MaterializeInc/materialize pull request #23341
Opened 2023-11-21 16:38 UTC by def-

Failure seen in https://buildkite.com/materialize/sql-logic-tests/builds/5743#018bf2a6-a95d-443c-a433-0b72a1ff84fd
@vmarcos I'm not sure I understand why this fails though. The query already returns an error, and so does creating the view.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2023-11-21 17:31 UTC, mjibson commented
I don't think this PR is right. From that build log:

```
SELECT pretty_sql('select 1,2,3', -1)
--
  | InconsistentViewOutcome:test/sqllogictest/pretty.slt:30
  | expected from query: Success
  | actually from indexed view: PlanFailure { error: db error: ERROR: Evaluation error: invalid width
```

The "expected from query: Success" should not be there because the directive is `query error db error: ERROR: invalid width`.

2023-11-21 18:22 UTC, vmarcos requested changes
I think this is a problem in the regex matching of the error messages. Locally, the following fixes it for me:
```diff
diff --git a/test/sqllogictest/pretty.slt b/test/sqllogictest/pretty.slt
index 044b45166d..444bebb2e9 100644
--- a/test/sqllogictest/pretty.slt
+++ b/test/sqllogictest/pretty.slt
@@ -26,14 +26,14 @@ SELECT pretty_sql('select 1,2,3', 100)
 ----
 SELECT 1, 2, 3;
 
-query error db error: ERROR: invalid width
+query error invalid width
 SELECT pretty_sql('select 1,2,3', -1)
 
-query error db error: ERROR: expected exactly one statement
+query error expected exactly one statement
 SELECT pretty_sql('select 1; select 2')
 
-query error db error: ERROR: expected exactly one statement
+query error expected exactly one statement
 SELECT pretty_sql('')
 
-query error db error: ERROR: expected exactly one statement
+query error expected exactly one statement
 SELECT pretty_sql(';')
```

2023-11-21 18:26 UTC, vmarcos commented
> I don't think this PR is right. From that build log:
> 
> ```
> SELECT pretty_sql('select 1,2,3', -1)
> --
>   | InconsistentViewOutcome:test/sqllogictest/pretty.slt:30
>   | expected from query: Success
>   | actually from indexed view: PlanFailure { error: db error: ERROR: Evaluation error: invalid width
> ```
> 
> The "expected from query: Success" should not be there because the directive is `query error db error: ERROR: invalid width`.

The outcome in `sqllogictest` is `Success` when there is a match to the directive (either a result or an error). The match occurs with the query in that the error message is in accordance with the one in the directive (so we get a `Success` outcome there), but the match does not occur with the view-based execution. This is because the error message then gets some extra pre-pendages and fails to match.

2023-11-21 21:10 UTC, mjibson commented
The above diff lgtm!

2023-11-21 22:48 UTC, def- commented
Thanks @vmarcos , I forgot about that again!

2023-11-22 02:21 UTC, mjibson approved these changes

2023-11-22 06:53 UTC, merged

2023-11-22 09:34 UTC, vmarcos commented
No worries, and thanks for bringing this over the finish line!