docs: Add docs for `ALTER ROLE ... SET ...` and `ALTER SYSTEM SET` for session variables
MaterializeInc/materialize pull request #24050
Opened 2023-12-20 17:18 UTC by ParkMyCar

This PR adds docs for the `ALTER ROLE ... SET ...` feature and documents that `ALTER SYSTEM SET ...` can be used to change the defaults for session variables.

### Motivation

Fixes https://github.com/MaterializeInc/materialize/issues/22107

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Updates user documentation for the `ALTER ROLE ... SET ...` feature, and documents the session defaults can be modified via `ALTER SYSTEM SET ...`

2023-12-28 12:08 UTC, morsapaes requested changes

2023-12-28 12:08 UTC, morsapaes commented on doc/user/layouts/shortcodes/session-variables.html
> +Name                                        | Default value             |  Description
```suggestion
Name                                        | Default value             |  Description                                                                                                                                                           | [Settable](../alter-system-set)
```

2023-12-28 12:08 UTC, morsapaes commented on doc/user/layouts/shortcodes/system-variables.html
> +changed, using `ALTER SYSTEM SET`.
```suggestion
Materialize reserves system variables for region-wide configuration. You must [contact us](https://materialize.com/contact/) to set the value
of _most_ variables to a different value than the provided default. System variables that can be modified by a _superuser_ (i.e. [`Organization Admin`](/manage/access-control/#role-based-access-control-rbac)) are marked as `Settable` below.
```

2023-12-28 12:08 UTC, morsapaes commented on doc/user/layouts/shortcodes/system-variables.html
>  Name                                        | Default value                                                         | Description
```suggestion
Name                                        | Default value                                                         | Description                                                                                                            | Settable |
```

2023-12-28 12:08 UTC, morsapaes commented
Thanks, @ParkMyCar!

2023-12-28 16:54 UTC, morsapaes commented on doc/user/layouts/shortcodes/system-variables.html
> +A subset of [session variables](../set/#session-variables) can also have their region-wide default
I find this confusing: you can set the default for _session_ variables using `ALTER SYSTEM`? Tried it out as an admin, and got:

```sql
ALTER SYSTEM SET cluster = 'other_cluster';

Error: permission denied to alter system
Detail: You must be the 'mz_system' role
```

2023-12-28 17:02 UTC, morsapaes commented
@jkosh44, just double-checking: am I supposed to be able to `ALTER ROLE` any role as a non-admin user? It seems a bit scary, and AFAIU you can only do this in PostgreSQL as a non-superuser if you have `CREATEROLE` privileges _and_ `ADMIN OPTION` privileges on the role you're trying to alter.

2023-12-28 17:59 UTC, jkosh44 commented
> @jkosh44, just double-checking: am I supposed to be able to `ALTER ROLE` any role as a non-admin user? It seems a bit scary, and AFAIU you can only do this in PostgreSQL as a non-superuser if you have `CREATEROLE` privileges _and_ `ADMIN OPTION` privileges on the role you're trying to alter.

Any role with the `CREATEROLE` system privilege can alter any other role (except for system roles such as `mz_system` and `mz_support`). We haven't implemented `ADMIN OPTION`, but maybe we can add the requirement of being a member of the target role.

2023-12-30 09:42 UTC, morsapaes commented
> Maybe we can add the requirement of being a member of the target role.

That makes sense to me.

2024-01-02 20:41 UTC, morsapaes approved these changes

2024-01-11 19:01 UTC, merged