compute: clean up join dispatch calls
MaterializeInc/materialize pull request #24343
Opened 2024-01-10 18:31 UTC by teskje

This PR cleans up the dispatch calls in join rendering code by simplifying the turbofish type annotations. Those are necessary because of compiler limitations, but they don't have to be as extensive as they previously were. Replacing most of them with `_` wildcards makes the code less boilerplate-y and also unbreaks rustfmt in one instance.

### Motivation

   * This PR refactors existing code.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - N/A

2024-01-10 20:57 UTC, frankmcsherry requested changes
I think there are a mix of good and bad things in here! There are moments where it changes from a specific type (e.g. `RowEnter`) to a less specific thing (`TraceEnter`) that I think is not great. There are some other moments where a lot of cruft gets removed that certainly looks nicer.

As the human who had to rip out the macros and wrangle Rust's glitchy type inference, I hope not to have to do that again soon. Adding them in was harder than removing them, I wager.

2024-01-11 08:52 UTC, teskje commented
> There are moments where it changes from a specific type (e.g. RowEnter) to a less specific thing (TraceEnter) that I think is not great. There are some other moments where a lot of cruft gets removed that certainly looks nicer.

The removal of cruft comes from replacing more specific types with less specific types (specifically, replacing nested types with wildcards). The approach taken here is to always use the least specific type annotations that still let the code compile. Given that the type annotations are only there to work around rustc limitations, rather than improving readability, and we would omit them if we could, I think that is a sensible approach to take. Can you speak more to why you think it's bad to use less specific types?

> As the human who had to rip out the macros and wrangle Rust's glitchy type inference, I hope not to have to do that again soon.

Rust is generally pretty careful about keeping existing code working with new Rust versions, so I'm not worried about Rust upgrades breaking the type inference. Is your concern about needing to change these type annotations when we make changes to the rendering code? In this case I would argue that having less specific annotations actually makes it less likely that we have to change them in the future.

Anyway, if the ask is just about using the `Row*` type aliases, that's fine with me. It doesn't change the result much.

2024-01-11 09:22 UTC, teskje commented
I added two more commits: The first one switching to the `Row*` type aliases, the second one introducing temporary aliases of the two enums to reduce the match patterns.

2024-01-11 11:31 UTC, vmarcos approved these changes
The latest iteration looks much clearer to me, so fine with me if @frankmcsherry is OK with it.

2024-01-16 16:28 UTC, frankmcsherry commented
> Can you speak more to why you think it's bad to use less specific types?

> Is your concern about needing to change these type annotations when we make changes to the rendering code? In this case I would argue that having less specific annotations actually makes it less likely that we have to change them in the future.

Yes. This was *not* the case in the most recent round of edits I made. We had less specific annotations, wrapped up in macros, and they had to be unpacked and manually specialized in order to accommodate DD improvements around GATs.

If landing these changes are more than a drive-by tidying, and do something specifically good for us, I'm supportive. I didn't see that in the PR desc though, and nothing leapt out to me from the PR itself.

2024-01-16 17:34 UTC, frankmcsherry approved these changes

2024-01-16 18:13 UTC, teskje commented
> Yes. This was not the case in the most recent round of edits I made. We had less specific annotations, wrapped up in macros, and they had to be unpacked and manually specialized in order to accommodate DD improvements around GATs.

Sorry about the macros, didn't mean for them to become painful!

> If landing these changes are more than a drive-by tidying, and do something specifically good for us, I'm supportive. I didn't see that in the PR desc though, and nothing leapt out to me from the PR itself.

The motivation for this change is that I'm trying out things around dataflow region rendering, and every time I touch the join rendering code these dispatch pieces are painful to deal with. So the specific good, apart from readability, is that the diff will be smaller if some of this makes it into a review.

2024-01-16 18:15 UTC, merged