sql: error when referencing ungrouped column that also exists in outer scope
MaterializeInc/materialize pull request #24354
Opened 2024-01-11 05:08 UTC by benesch

Our existing code for detecting references to columns that did not appear in the GROUP BY clause or an aggregate function did not consider the case that a column of the same name existed in the outer scope. Per PostgreSQL, the correct behavior is to bind to the column reference in the inner scope and error due to the lack of grouping, rather than to successfully bind to the column reference in the outer scope.

Fix #23748.
Fix #24328.

### Motivation

  * This PR fixes a recognized bug.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [x] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [x] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [x] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [x] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - Fix a correctness issue with subqueries that referred to ungrouped columns when columns of the same name existed in an outer scope.

2024-01-11 07:50 UTC, nrainer-materialize approved these changes

2024-01-11 14:07 UTC, philip-stoev commented
The error messages now match Postgres's in the randomized workload where the original bug came from . I noticed that between the two bugs closed and the comments within there are multiple queries known to exhibit the same problem, while the SLT test only has one. Would it make sense to push all available test cases just in case.

2024-01-11 14:07 UTC, philip-stoev approved these changes

2024-01-11 14:50 UTC, benesch commented
Happy to have more tests!

On Thu, Jan 11, 2024 at 9:07 AM Philip Stoev ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/MaterializeInc/materialize/pull/24354#pullrequestreview-1815672541>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAGXSIAL3SCXX3NT7SCHD2LYN7W2LAVCNFSM6AAAAABBV4GE66VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQMJVGY3TENJUGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-01-11 15:25 UTC, nrainer-materialize commented
> Happy to have more tests!

I have added a few test cases with https://github.com/MaterializeInc/materialize/pull/24354/commits/0e851c970e2b897f93ecc1dd0d886b5160cb8479.

I am not convinced by the result of two queries:
```
SELECT (SELECT sum(b) FROM t WHERE b = 2 GROUP BY a) FROM t t1 GROUP BY t1.b;
```
and
```
SELECT t1.a, (SELECT t2.a FROM t t2 WHERE t2.b = 2 AND t1.b = t2.b GROUP BY t2.a) FROM t t1;
```
produce a query error with `more than one record produced in subquery` but this is not the case in my opinion...
Any thoughts?

2024-01-11 17:34 UTC, mjibson approved these changes

2024-01-12 05:16 UTC, benesch commented
> produce a query error with more than one record produced in subquery but this is not the case in my opinion...

They do? In my testing, and in the latest CI run with those tests, they seem to produce the same answers as PostgreSQL?

2024-01-12 07:55 UTC, nrainer-materialize commented
> They do? In my testing, and in the latest CI run with those tests, they seem to produce the same answers as PostgreSQL?

I double-checked and it is ok. I fixed the test case.

2024-01-12 09:08 UTC, nrainer-materialize commented
I updated the explain plans in the SLT tests for your convenience but please have a quick look at whether this is as expected: https://github.com/MaterializeInc/materialize/pull/24354/commits/0030f2b2a81f6896990c119246cc08d818c268f6

2024-01-12 09:14 UTC, nrainer-materialize commented
Further SLT build: https://buildkite.com/materialize/sql-logic-tests/builds/5796

2024-01-12 11:05 UTC, nrainer-materialize commented
Please note that there are some further build failures:
* Cargo test: https://buildkite.com/materialize/tests/builds/72950#018cfcee-fa14-4bb2-b8fc-f407ca84fcaf
* Testdrive: https://buildkite.com/materialize/tests/builds/72950#018cfcee-fa1a-4448-959d-af05fa1b1d93 (easy to fix, but is this expected?)
* SQL Logic Tests 3: https://buildkite.com/materialize/sql-logic-tests/builds/5796#018cfcf3-f847-45e4-9c1e-d18e275933db (requires `enable_table_keys` to be enabled but wondering why this succeeded before; can analyzer further if needed)
* SQL Logic Tests 10: https://buildkite.com/materialize/sql-logic-tests/builds/5796#018cfcf3-f849-4211-b4cb-c7bcda184ce0 (fails with `column name "name" appears more than once in USING clause not yet supported` errors)

2024-01-15 08:16 UTC, nrainer-materialize commented
I triggered new builds:
* https://buildkite.com/materialize/nightlies/builds/5983
* https://buildkite.com/materialize/sql-logic-tests/builds/5798

2024-01-15 12:29 UTC, ggevay requested changes
Unfortunately, many slt plans regressed. There are several cases where a CrossJoin appears where there was an equi join before. Also, plans seem generally larger.

2024-01-15 12:29 UTC, ggevay commented on test/sqllogictest/chbench.slt
> +          CrossJoin type=differential // { arity: 2 }
Why has this equi join turned into a CrossJoin?

2024-01-15 12:29 UTC, ggevay commented on test/sqllogictest/ldbc_bi.slt
> +          CrossJoin type=differential // { arity: 2 }
same here

2024-01-15 12:29 UTC, ggevay commented on test/sqllogictest/subquery.slt
> +        CrossJoin type=differential // { arity: 2 }
same here

2024-01-15 12:29 UTC, ggevay commented on test/sqllogictest/subquery.slt
> +        CrossJoin type=differential // { arity: 2 }
same here

2024-01-15 13:02 UTC, nrainer-materialize commented
> I triggered new builds:
> 
>     * https://buildkite.com/materialize/nightlies/builds/5983

As for the nightly build,
* "Feature benchmark against merge base or 'latest'" should be fixed by a rebase
* "🏎️ testdrive with SIZE 8" failed on main (and might also be fixed by now)
* "Persist-txn fencing" failed on main (and might be fixed by now)

Other checks should be looked at. Some may disappear after a rebase with main. Let me know if you need any support!

2024-01-16 04:12 UTC, benesch commented
> Unfortunately, many slt plans regressed. There are several cases where a CrossJoin appears where there was an equi join before. Also, plans seem generally larger.

Yeah, I noticed that too. Our optimizer was not as effective as I was hoping at using projection pushdown to eliminate the dead dummy columns. I'm working on an alternative implementation that doesn't cause the plans to change.

2024-01-29 05:56 UTC, benesch commented
Ok, pushed up a rewritten implementation that does not rely on injecting dummy datums into the HIR plan, since that was causing the optimizer to regress substantially on a large swath of plans. 

@ggevay @nrainer-materialize PTAL!

2024-01-29 06:02 UTC, benesch commented
Nightlies: https://buildkite.com/materialize/nightlies/builds/6196
SLT: https://buildkite.com/materialize/sql-logic-tests/builds/5816

2024-01-29 10:55 UTC, nrainer-materialize commented
Thank you, LGTM!

2024-01-29 17:54 UTC, ggevay approved these changes

2024-01-30 02:22 UTC, merged

2024-01-30 02:22 UTC, benesch commented
Thanks for the (double) reviews on this one, y'all!