Shepherdly config
MaterializeInc/materialize pull request #24438
Opened 2024-01-15 15:01 UTC by mgreene

Shepherdly now supports `yml` config at the repo level as well as custom mitigations.

Another notable change is the support of custom mitigations. Per @def-'s [request](https://shepherdly.slack.com/archives/C051BG4BFL7/p1704815224163999), I've added a custom mitigation that links out to running nightly tests. 

Everything else in the file is a copy of how the repo settings were configured to date.

### Motivation
Shepherdly is moving towards injectable configuration and this change brings the `materialize` repo up to parity.

2024-01-15 15:23 UTC, def- approved these changes
Perfect, thank you!

2024-01-15 18:03 UTC, def- commented
I don't have permission to push into your branch:
```
ERROR: Permission to shepherdlyinc/materialize.git denied to def-.
```

To get the linting green you can add this (or give me push permissions):
```diff
diff --git a/.config/shepherdly.yml b/.config/shepherdly.yml
index ff94997c22..b08b501d21 100644
--- a/.config/shepherdly.yml
+++ b/.config/shepherdly.yml
@@ -1,3 +1,12 @@
+# Copyright Materialize, Inc. and contributors. All rights reserved.
+#
+# Use of this software is governed by the Business Source License
+# included in the LICENSE file at the root of this repository.
+#
+# As of the Change Date specified in that file, in accordance with
+# the Business Source License, use of this software will be governed
+# by the Apache License, Version 2.0.
+#
 # Docs: https://help.shepherdly.io/en/articles/8818618-shepherdly-repo-config
 configurations:
   - name: scoring_comment_enabled
@@ -31,4 +40,4 @@ mitigations:
     custom: true
     label: Run Nightly Tests
     label_url: https://trigger-ci.dev.materialize.com/?pr={{pr_number}}
-default_system_mitigations: false
\ No newline at end of file
+default_system_mitigations: false
```

2024-01-15 18:47 UTC, def- requested changes

2024-01-15 18:47 UTC, def- commented on .config/shepherdly.yml
> +default_system_mitigations: false
Still no newline at the end of file (thus not a valid file in the POSIX sense)

2024-01-15 22:15 UTC, def- approved these changes

2024-01-15 22:15 UTC, def- commented on .config/shepherdly.yml
> +
Now it's two newlines, but doesn't matter ;)

2024-01-15 22:19 UTC, def- commented on .config/shepherdly.yml
> +
Actually does matter: `.config/shepherdly.yml:45: new blank line at EOF.`

2024-01-15 22:41 UTC, closed without merging

2024-01-16 07:41 UTC, nrainer-materialize commented
This PR contains unrelated commits, I assume a rebase went wrong.