support `EXPLAIN REPLAN [INDEX | MATERIALIZED VIEW]`
MaterializeInc/materialize pull request #25026
Opened 2024-02-06 20:51 UTC by aalexandrov

### Motivation

  * This PR adds a feature that has not yet been specified.

I don't think we have an issue for that, but currently there is no way to inspect how a plan would differ if we enable an optimizer feature flag and then restart `environmentd`. A naive solution might be to lookup the `CREATE` statement for a catalog item from the catalog and then run

```sql
EXPLAIN CREATE <catalog item>
```

However, this doesn't work because:

1. The catalog state considered when we run `EXPLAIN CREATE <catalog item>` might be different from the catalog state available when re-planning during `bootstrap`.
2. Our external tooling soon won't be able to lookup valid `CREATE` statements for all catalog items because they are not redacted (and the redacted versions are not valid SQL).

To solve both issues we introduce new (for now undocumented) syntax:

```sql
EXPLAIN REPLAN CATALOG ITEM <name>;
EXPLAIN REPLAN INDEX <name>;
```

That can be used in conjunction with optimizer feature flags passed with `EXPLAIN WITH(...)` to inspect a catalog for plan regressions and plan improvements before rolling out a change.

### Tips for reviewer

It's best to review one commit at a time.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2024-02-07 17:06 UTC, ggevay requested changes

2024-02-07 17:06 UTC, ggevay commented on test/sqllogictest/explain/replan_catalog_items.slt
Could you add a test where EXPLAIN and EXPLAIN REPLAN should not coincide?

I tried the following, but somehow the replan didn't pick up enable_eager_delta_joins:

```
create table t1(x int, y int);
create table t2(x int, y int);
create table t3(x int, y int);

create materialized view mv1 as
select t1.y as c1, t2.y as c2, t3.y as c3
from t1, t2, t3
where t1.x = t2.x and t2.y=t3.y;

explain materialized view mv1;

explain with(enable_eager_delta_joins) replan materialized view mv1;
```

(If I globally enable/disable the flag, then I get different plans for the first explain.)

2024-02-07 21:19 UTC, jkosh44 approved these changes

2024-02-08 13:03 UTC, ggevay approved these changes

2024-02-08 14:00 UTC, merged