adapter: only do a single pass with ExprPrepStyle
MaterializeInc/materialize pull request #25222
Opened 2024-02-14 06:38 UTC by mjibson

This was a remnant from when the optimizer was in two steps and the timestamp was determined between them. Now that we always have it, only do a single unmat fn resolution.

### Motivation

   * This PR refactors existing code.

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  - n/a

2024-02-14 14:59 UTC, ParkMyCar approved these changes

2024-02-15 08:09 UTC, aalexandrov approved these changes

2024-02-15 08:10 UTC, aalexandrov commented
I tried to do that in #25113 but then realized that this breaks a whole bunch of tests because `mz_now()` is now substituted with a time-varying integer. See [my comment for details](https://github.com/MaterializeInc/materialize/pull/25113#issuecomment-1935971378)

2024-02-15 08:16 UTC, aalexandrov requested changes
Current changes look good, but I don't think this will be enough.

I already tried to do exactly that in #25113, but then realized that this breaks a whole bunch of our CI tests because `mz_now()` is now substituted with a time-varying integer. Looking at the tests failed [in this build](https://buildkite.com/materialize/tests/builds/75652) and [the failed build in my PR](https://buildkite.com/materialize/tests/builds/75287) it seems this is hitting the same issue. I suggest to leave this open until we figure a way to fix the broken `*.slt` tests in a way similar to `*.td`.

See [my comment in #25113 for details](https://github.com/MaterializeInc/materialize/pull/25113#issuecomment-1935971378).

2024-02-15 16:38 UTC, mjibson commented
Thanks for the reference! Agree and leaving as is for now then.

2024-02-15 16:38 UTC, closed without merging