storage: prevent load generators with unused options
MaterializeInc/materialize pull request #26080
Opened 2024-03-15 21:40 UTC by guswynn

This is https://github.com/MaterializeInc/materialize/pull/26006, but with tests fixed with version checks (thanks @def- for the good docs!), as well as a fixed migration. Because some migrations want to happen pre-planning, but some need a catalog connection, we split the migration code into two phases.

### Motivation
  * This PR fixes a recognized bug.

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2024-03-16 06:57 UTC, def- requested changes

2024-03-16 06:57 UTC, def- commented on misc/python/materialize/checks/all_checks/cluster_unification.py
> +                >[version<9200] CREATE SOURCE shared_cluster_storage_first_source
I think we're already on v0.93.0-dev already, so would be better to go up one version here and below.

2024-03-18 13:41 UTC, jkosh44 approved these changes

2024-03-18 16:22 UTC, def- approved these changes
Thanks!

2024-03-18 16:24 UTC, merged