ci: feature benchmark: annotate regressions
MaterializeInc/materialize pull request #26627
Opened 2024-04-12 16:23 UTC by nrainer-materialize

I did not check the annotation on a real build but the generated junit xml file looked reasonable.

I will add something similar for the scalability framework after my holidays.

2024-04-12 16:25 UTC, nrainer-materialize commented
@def-: Feel free to click the merge button if it looks ok.

2024-04-13 00:49 UTC, def- requested changes

2024-04-13 00:49 UTC, def- commented on misc/python/materialize/feature_benchmark/benchmark.py
> +    def print(self) -> None:
This helper seems kind of useless ;)

2024-04-13 00:49 UTC, def- commented on test/feature-benchmark/mzcompose.py
> +            report.print()
Could just call `print(report)` here.

2024-04-13 00:51 UTC, def- approved these changes

2024-04-13 01:25 UTC, merged