storage: accept require/required interchangeably
MaterializeInc/materialize pull request #27238
Opened 2024-05-22 20:14 UTC by guswynn

Based https://materializeinc.slack.com/archives/C04LQV4KUR4/p1716405259031939

Also changed some random tests to test the change

### Motivation

  * This PR adds a known-desirable feature.

### Checklist

- [x] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2024-05-22 20:55 UTC, alex-hunt-materialize approved these changes

2024-05-22 23:26 UTC, maddyblue approved these changes

2024-05-23 01:23 UTC, sploiselle requested changes
These options should be made mutually exclusive. https://github.com/MaterializeInc/materialize/blob/main/src/sql/src/plan/statement/ddl/connection.rs#L80

2024-05-23 15:31 UTC, guswynn commented
@sploiselle these are strings that occur after the `SSL MODE = 'string'` option, so no overlap is occurring

2024-05-23 16:06 UTC, sploiselle approved these changes

2024-05-23 16:07 UTC, sploiselle commented
@guswynn Ah! ty for clarifying

2024-05-23 16:16 UTC, merged