Update user docs on webhook source creation to use an alias for the CHECK statement secret
MaterializeInc/materialize pull request #27572
Opened 2024-06-11 18:47 UTC by chaas

Docs counterpart to https://github.com/MaterializeInc/console/pull/2537.
Tested this example out in staging and it worked.

cc @arusahni 

### Motivation

This PR adds a feature that has not yet been specified.

The CHECK statement syntax can be confusing to people. One aspect that is challenging is that you cannot use a fully qualified name for the secret in the constant_time_eq call. Let's encourage users to alias the secret, then use the alias in the constant_time_eq call. 

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] This PR includes the following [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note):
  -

2024-06-11 18:49 UTC, arusahni approved these changes

2024-06-11 18:55 UTC, morsapaes requested changes
Encouraging by using the best practice in the example is fine, but we should document it explicitly, too.

2024-06-11 19:23 UTC, chaas commented
> Encouraging the best practice by using it in the example is fine, but we should document it explicitly, too.

It's already documented as optional in the RR diagram & `SECRET` field description:

> Provide a secret_name column to the check expression, with the value of the [SECRET](https://materialize.com/docs/sql/create-secret). The column can be renamed with the optional AS alias statement, and the type can be changed to bytea with the optional BYTES keyword.

Should we be more explicit and say that we recommend using the alias? E.g. adding another sentence

> For ease of use, we recommend renaming the column with the AS alias, for example `SECRET _secret_name_ AS validation_secret`.

2024-06-11 21:14 UTC, ParkMyCar approved these changes

2024-06-12 01:55 UTC, morsapaes approved these changes
Pushed a suggestion for the blurb, and adapted the integration guides to also include the note about secret namespacing.

2024-06-12 15:17 UTC, merged