docs: Add section headings to ingest data postgres pages
MaterializeInc/materialize pull request #28329
Opened 2024-07-17 21:40 UTC by kay-kim

Just adding section headings.  This will make it easier going forward to update the contents on these pages (particularly, as some steps can be more easily performed in the console).

2024-07-17 23:01 UTC, morsapaes requested changes

2024-07-17 23:01 UTC, morsapaes commented on doc/user/content/ingest-data/postgres/self-hosted.md
> +  enabled; i.e., verify `wal_level` setting is set to `logical`.
```suggestion
  enabled (i.e., verify `wal_level` setting is set to `logical`).
```

2024-07-17 23:01 UTC, morsapaes commented on doc/user/content/ingest-data/postgres/self-hosted.md
> +## C. Ingest Data in Materialize
```suggestion
## C. Ingest data in Materialize
```

2024-07-18 15:21 UTC, kay-kim commented on doc/user/content/ingest-data/postgres/alloydb.md
> +### 3. Check the ingestion status
👍 Ah, got it. Because all the others had "Check", I thought maybe we just forgot to update it. Will update to all to Monitor in next patch.

2024-07-18 15:22 UTC, kay-kim commented on doc/user/content/ingest-data/postgres/debezium.md
> +1. Start the Debezium Postgres connector using the configuration file:
👍 Will update in next patch.

2024-07-18 15:23 UTC, kay-kim commented on doc/user/content/ingest-data/postgres/debezium.md
> +## D. Create a materialized view
Heh heh ... noticed that too. Oh, 💯  on pointing to indexed views.

2024-07-18 17:29 UTC, morsapaes approved these changes

2024-07-18 17:47 UTC, merged