unsafe session var to enable superuser
MaterializeInc/materialize pull request #30316
Opened 2024-11-02 02:43 UTC by jubrad

### Motivation
Add an unsafe param that allow the current user to set themselves up as a superuser. This is mean to be used for testing superuser specific behavior and privileges. 

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

2024-11-04 14:10 UTC, jkosh44 commented on src/sql/src/session/vars/definitions.rs
> +);
I think it's worth adding a test to this file, https://github.com/MaterializeInc/materialize/blob/main/src/environmentd/tests/server.rs, that starts a server without unsafe mode and asserting that we do not allow setting this variable.

2024-11-04 14:11 UTC, jkosh44 commented on src/sql/src/session/vars/definitions.rs
> +);
Probably also worth testing that setting this variable in unsafe mode actually gives the user superuser privileges.

2024-11-08 17:18 UTC, ParkMyCar requested changes
This is a bit scary to me because a bug could allow anyone to become a superuser. An alternative I would like to propose is integrating our [`frontegg-mock`](https://github.com/MaterializeInc/materialize/tree/main/src/frontegg-mock) with testdrive. We could have a specific testdrive action which communicates with the frontegg mock and grants "external admin"/superuser status to role

2024-11-09 05:52 UTC, jubrad commented
frontegg mock in TD is probably a better idea.
The other suggestion is to add `create role ... with superuser` which is maybe a good idea as well.

If we do want to keep something like this flag a safer option might be a SystemVar only modifiable by mz_system that promotes a user (or list of users) by name to superuser. If that were also unsafe then you'd have to have several bugs in coordination to have superuser privilege escalation.

2025-02-07 17:38 UTC, closed without merging