materialized image: Strip debug symbols
MaterializeInc/materialize pull request #30571
Opened 2024-11-19 19:40 UTC by def-

I'm not exactly sure if we want that. If we still upload the debug info to debuginfo.dev.materialized.com, we can still make use of it. Do we lose much else?

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered. ([trigger-ci for additional test/nightly runs](https://trigger-ci.dev.materialize.com/))
- [ ] This PR has an associated up-to-date [design doc](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/README.md), is a design doc ([template](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/design/00000000_template.md)), or is sufficiently small to not require a design.
  
- [ ] If this PR evolves [an existing `$T ⇔ Proto$T` mapping](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/command-and-response-binary-encoding.md) (possibly in a backwards-incompatible way), then it is tagged with a `T-proto` label.
- [ ] If this PR will require changes to cloud orchestration or tests, there is a companion cloud PR to account for those changes that is tagged with the release-blocker label ([example](https://github.com/MaterializeInc/cloud/pull/5021)).
  
- [ ] If this PR includes major [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/developer/guide-changes.md#what-changes-require-a-release-note), I have pinged the relevant PM to schedule a changelog post.

2024-11-19 19:46 UTC, antiguru commented
This might have been an accidental change from me I didn't mean to merge. Lgtm if you want to merge.

2024-11-19 20:07 UTC, ParkMyCar reviewed
I think it's nice having the symbols in the image for the emulator so we can get back traces.... but now that I think about it, we still get backtraces from the `environmentd` and `clusterd` images, so I don't think I totally understand the scope of what strip does?

2024-11-19 21:12 UTC, benesch requested changes
Yeah agreed—I worry that if we strip the `materialized` binary we'll never be able to track down emulator crashes because we won't have backtraces.

2024-11-19 21:39 UTC, def- commented
This shoulds affect tools like gdb/lldb/polarsignals which can be taught to use http://debuginfo.dev.materialize.com to fetch the info. Panics look a bit more annoying:
```
thread 'main' panicked at src/materialized/src/bin/materialized.rs:18:18:
Unknown executable: Some("materialized")
stack backtrace:
   0:     0x5d79ff96a915 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x5d79f55a7c7b - core::fmt::write::hc6043626647b98ea
   2:     0x5d79ff965fbf - std::io::Write::write_fmt::h0d24b3e0473045db
   3:     0x5d79ff96a6ee - std::sys_common::backtrace::print::h45eb8174d25a1e76
   4:     0x5d79ff96c659 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   5:     0x5d79ff96c405 - std::panicking::default_hook::hb5d3b27aa9f6dcda
   6:     0x5d79ff96cb46 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   7:     0x5d79ff96ca44 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   8:     0x5d79ff96add9 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
   9:     0x5d79ff96c797 - rust_begin_unwind
  10:     0x5d79f55a4353 - core::panicking::panic_fmt::ha02418e5cd774672
  11:     0x5d79f5b37786 - materialized[5cf4fd8902c065d4]::main
  12:     0x5d79f5b37843 - std[fba9fafec3bdacf8]::sys_common::backtrace::__rust_begin_short_backtrace::<fn(), ()>
  13:     0x5d79f5b37809 - std[fba9fafec3bdacf8]::rt::lang_start::<()>::{closure#0}
  14:     0x5d79ff95e263 - std::rt::lang_start_internal::hcee5ed89fc25829a
  15:     0x5d79f5b377fc - main
  16:     0x7042cea28150 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  17:     0x7042cea28209 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  18:     0x5d79f4aa8021 - _start
  19:                0x0 - <unknown>
```
Something like addr2line could be used in CI and provided as a script to get the file:line combinations back.
Docker image size would go down to 236 MB with this change: https://hub.docker.com/layers/materialize/materialized/v0.126.0-dev.0--pr.g9360ebd5473a5bf3d670f08baa90cc2fb2c09740/images/sha256-8d8c4fd6d58b77f50101364104d3e780ad5a8e9d7585e77888975cf2e7dd8e48?context=explore
I agree though that it might be a bit annoying in CI, so ok for me not to merge. It would be important to set RUST_BACKTRACE=full to actually get the addresses to look up.

2024-11-19 21:39 UTC, closed without merging

2024-11-20 04:14 UTC, umanwizard commented
@benesch I wasn't suggesting you strip all the symbols (which includes function names etc.)... just the debug symbols!

So as Dennis's comment shows, you would still get backtraces, just without line numbers and inlined functions. (If you stripped everything, you'd get a bunch of `<unknown>`).

Whether that's worth the tradeoff for improved binary size is up to you. I just wanted to make sure people were aware that this is possible (since I'm the one who set it up while I was at MZ).

Either way, this should not impact symbolization in PS since you're uploading the debug info regardless. I also checked with `debug = "line-tables-only"` (which you recently downgraded to from `debug = "full"`) and we still get good symbolization with that, so nothing should be broken from our perspective (but do let us know if anything looks weird.)

2024-11-20 16:34 UTC, benesch commented
Yeah sorry, I agree—but worried about how much less usable a backtrace is without line numbers. @def-'s idea about running addr2linemanually seems workable though, though. Chatting on Slack about this now.