support internal representation of new map type
MaterializeInc/materialize pull request #4801
Opened 2020-11-16 16:40 UTC by JLDLaughlin

This PR enables Materialize to represent maps internally by adding a `Map` variant to the
required enums. To test this, I've added the ability to parse strings as maps.

2020-11-17 07:02 UTC, benesch reviewed
:tada: This is in really good shape! Left you some comments within about simplifying some of the parsing/formatting code, and also about a potential escaping bug.

> Reviewed 7 of 7 files at r1, 9 of 9 files at r2, 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801#-:-MMK-VO_5wcDSkWt2tfV:boh5ydg)* status: all files reviewed, 18 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[src/expr/src/scalar/func.rs, line 3315 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJzMbO6f8G3MSMYR2E:-MMJzMbPBvVlON3d1ML-:bcl6x5q) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/expr/src/scalar/func.rs#L3315)):*
> ```Rust
>         }),
>         Map(elem_type) => {
>             let dict: Vec<(&str, Datum)> = d.unwrap_dict().iter().map(|(k, v)| (k, v)).collect();
> ```

See comment below about using `IntoIterator` on `format_map` to avoid creating the intermediate vec!
___
*[src/pgrepr/src/types.rs, line 55 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJp_1S9JcRM-uI2IOf:-MMJp_1T5dHZIKyQcobL:b-1klxg6) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/pgrepr/src/types.rs#L55)):*
> ```Rust
>     Oid,
>     /// A map with text keys and homogeneous values.
>     Map(Box<Type>),
> ```

Can you use a struct variant, just to make this a bit more clear and since we'll probably add a key type eventually?

```
Map {
    value_type: Box<Type>,
}
```
___
*[src/pgrepr/src/value.rs, line 474 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJqU-Z0YUe52vDTv_D:-MMJqU-Z0YUe52vDTv_E:b-9apkgj) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/pgrepr/src/value.rs#L474)):*
> ```Rust
>     pairs.sort_by(|(k1, _v1), (k2, _v2)| k1.cmp(k2));
>     pairs.dedup_by(|(k1, _v1), (k2, _v2)| k1 == k2);
>     strconv::format_map(buf, pairs, |buf, elem| match elem {
> ```

Not sure I understand what's going on here! If we want to sort things alphabetically on output, then I think just make the `HashMap` into a `BTreeMap`? Creating a new vec and sorting and deduping is gonna be a bit expensive. Also would be good if `format_map` took `IntoIterator<Item = (&str, T)>` so that you can pass in the hashmap directly! (Might require some more futzing with the types, but the spirt of that is correct.)
___
*[src/repr/src/scalar.rs, line 704 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJqvDv9hFVsV50GBMl:-MMJqvDv9hFVsV50GBMm:b-nmzzaj) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/scalar.rs#L704)):*
> ```Rust
>     /// Values within the map are of the specified type. Values may always
>     /// be [`Datum::Null`].
>     Map(Box<ScalarType>),
> ```

Ditto here on struct type.
___
*[src/repr/src/scalar.rs, line 769 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJxtu3Cl31FCt37XTC:-MMJxtu3Cl31FCt37XTD:bfrfnjq) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/repr/src/scalar.rs#L769)):*
> ```Rust
>     ///
>     /// Panics if called on anything other than a [`ScalarType::Map`].
>     pub fn unwrap_map_element_type(&self) -> &ScalarType {
> ```

s/map_element_type/map_value_type/
___
*[src/repr/src/strconv.rs, line 710 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJyz8P639W4WGKsw04:-MMJyz8P639W4WGKsw05:b-c9z30x) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L710)):*
> ```Rust
>     s: &'a str,
>     mut gen_key: impl FnMut(Cow<'a, str>) -> String,
>     mut gen_elem: impl FnMut(Cow<'a, str>) -> Result<V, E>,
> ```

`gen_key` right now just calls `.into_owned()` on the `Cow` (and probably can't possibly do anything more clever than that). I'd just ditch it and call `.into_owned()` on the `Cow` yourself in this method to keep things simple. Also minor nit: maybe `gen_value` instead of `gen_elem`?
___
*[src/repr/src/strconv.rs, line 740 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJyT6G9aB1XY0MILjx:-MMJyT6HA2RosAZ22G2k:bh70m9g) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L740)):*
> ```Rust
>             None => bail!("unexpected end of input"),
>         };
>         let key = gen_key(key.unwrap());
> ```

This call to `unwrap` looks worrying. How do you know `map_lex_unquoted_element` won't return `None`?
___
*[src/repr/src/strconv.rs, line 749 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJudk54mdDV-ReB4Q7:-MMJudk54mdDV-ReB4Q8:b-mtxvj2) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L749)):*
> ```Rust
>         if !buf.consume('>') {
>             bail!("expected >")
>         }
> ```

This is logically one symbol, so I think it'll be a little weird if you get an error message about a missing `=` or `>`. Maybe something like this?

```rust
if !buf.consume('=') || !buf.consume('>') {
    bail!("expected =>")
}
```
___
*[src/repr/src/strconv.rs, line 830 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJydD370muWs8TTbs_:-MMJydD370muWs8TTbsa:b-bdeeoq) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L830)):*
> ```Rust
>             Some('=') if buf.peek() == Some('>') => {
>                 // An arrow indicates as the first characters indicates missing
>                 // key information.
> ```

Is this always true? What about for values?
___
*[src/repr/src/strconv.rs, line 865 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJvI7XBB8XMAjzkRVb:-MMJvI7XBB8XMAjzkRVc:b4zbbu6) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L865)):*
> ```Rust
>         Some(Cow::Owned(s))
>     })
> }
> ```

It'd be really great if we could share this method with the list parsing code because it is so darn complicated. What do you think about just plumbing an `is_map` bool into that function? I think you can even leave `>` as a non-special char in the map case, because it only becomes special if it follows an `=` sign.
___
*[src/repr/src/strconv.rs, line 880 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJu4ex0EhXc1Qk7cxJ:-MMJu4ex0EhXc1Qk7cxK:b-t7kp8m) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L880)):*
> ```Rust
>         buf.write_str(key);
>         buf.write_str("=>");
>         format_elem(MapElementWriter(buf), value);
> ```

This looks like it doesn't handle escaping the value?
___
*[src/repr/src/strconv.rs, line 1072 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJuFHA9hV6rXbcC4IS:-MMJuFHA9hV6rXbcC4IT:blgzln9) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L1072)):*
> ```Rust
> /// A helper for `format_map` that formats a single map key, value pair.
> #[derive(Debug)]
> pub struct MapElementWriter<'a, F>(&'a mut F);
> ```

Maybe call this `MapValueWriter` since it only formats a single map value? Also I think the comment incorrectly states that it formats the key too.
___
*[src/sql/src/plan/typeconv.rs, line 647 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMK-Prc660Gr5QGJ1N2:-MMK-Prd4iTSfY9Hexcm:b-k2j6q2) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/sql/src/plan/typeconv.rs#L647)):*
> ```Rust
>         _ => unreachable!("already  [...]

2020-11-17 21:47 UTC, JLDLaughlin reviewed
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801)* status: 6 of 18 files reviewed, 18 unresolved discussions (waiting on @benesch, @JLDLaughlin, and @sploiselle)

___
*[src/expr/src/scalar/func.rs, line 3315 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJzMbO6f8G3MSMYR2E:-MMMzckV18qeMd1tZSDO:bx3xple) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/expr/src/scalar/func.rs#L3315)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

See comment below about using `IntoIterator` on `format_map` to avoid creating the intermediate vec!
</blockquote></details>

I was able to avoid creating the intermediate map in the other case! Fixing it in this case, and updating `format_map` to take `IntoIterator<Item = (&str, T)>` (instead of `IntoIterator<Item = (&'a String, T)>), would require introducing a `'a` lifetime for pgrepr's `Type`. I'm happy to do that, but it seemed like a decently large change.
___
*[src/pgrepr/src/types.rs, line 55 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJp_1S9JcRM-uI2IOf:-MMMLjz5AAq0pi3X-Vd4:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/pgrepr/src/types.rs#L55)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Can you use a struct variant, just to make this a bit more clear and since we'll probably add a key type eventually?

```
Map {
    value_type: Box<Type>,
}
```
</blockquote></details>

Done.
___
*[src/pgrepr/src/value.rs, line 474 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJqU-Z0YUe52vDTv_D:-MMMVEyKE-GS8XD66qF1:b-xhu2iv) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/pgrepr/src/value.rs#L474)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Not sure I understand what's going on here! If we want to sort things alphabetically on output, then I think just make the `HashMap` into a `BTreeMap`? Creating a new vec and sorting and deduping is gonna be a bit expensive. Also would be good if `format_map` took `IntoIterator<Item = (&str, T)>` so that you can pass in the hashmap directly! (Might require some more futzing with the types, but the spirt of that is correct.)
</blockquote></details>

I remembered getting some sort of "key out of order" error, but I'm not able to reproduce it or find it now. The other issue is that the key/value pairs come back in any order without this sort, which makes asserting the value of multi-key maps impossible in tests.

Thinking about it, maybe this sorting hack should exist in sqllogictest instead?
___
*[src/repr/src/scalar.rs, line 704 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJqvDv9hFVsV50GBMl:-MMMNrDQ8FGpoCUo_H9P:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/scalar.rs#L704)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ditto here on struct type.
</blockquote></details>

Done.
___
*[src/repr/src/scalar.rs, line 769 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJxtu3Cl31FCt37XTC:-MMNA35bCif8eAljLNqr:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/repr/src/scalar.rs#L769)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

s/map_element_type/map_value_type/
</blockquote></details>

Done.
___
*[src/sql/src/plan/typeconv.rs, line 692 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJxbRG-wYKLM_pGUWQ:-MMMqpmq6f4JJRAL6tnV:bxxx4g2) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/sql/src/plan/typeconv.rs#L692)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Super minor, but maybe put the experimental mode check before the nested map check, just to really enforce that you can't even get error messages about maps unless in experimental mode.
</blockquote></details>

That makes sense!
___
*[src/sql-parser/src/ast/defs/value.rs, line 236 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJpuwV1xa_UGR1YuFz:-MMMSLAXAr9KM4jcV76q:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/sql-parser/src/ast/defs/value.rs#L236)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ditto here on using a struct variant!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-17 22:08 UTC, JLDLaughlin reviewed
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801)* status: 5 of 18 files reviewed, 18 unresolved discussions (waiting on @benesch, @JLDLaughlin, and @sploiselle)

___
*[src/repr/src/strconv.rs, line 710 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJyz8P639W4WGKsw04:-MMNC3FnAS6ibh1R2DZP:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L710)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

`gen_key` right now just calls `.into_owned()` on the `Cow` (and probably can't possibly do anything more clever than that). I'd just ditch it and call `.into_owned()` on the `Cow` yourself in this method to keep things simple. Also minor nit: maybe `gen_value` instead of `gen_elem`?
</blockquote></details>

Done.
___
*[src/repr/src/strconv.rs, line 740 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJyT6G9aB1XY0MILjx:-MMNC5Yr2VgGt0_c14ok:bt2vr0y) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L740)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This call to `unwrap` looks worrying. How do you know `map_lex_unquoted_element` won't return `None`?
</blockquote></details>

Fixed!
___
*[src/repr/src/strconv.rs, line 749 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJudk54mdDV-ReB4Q7:-MMNCIzLEGryWvG5CIsD:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L749)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This is logically one symbol, so I think it'll be a little weird if you get an error message about a missing `=` or `>`. Maybe something like this?

```rust
if !buf.consume('=') || !buf.consume('>') {
    bail!("expected =>")
}
```
</blockquote></details>

Done.
___
*[src/repr/src/strconv.rs, line 830 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJydD370muWs8TTbs_:-MMNCaqa5HajL8F_CPIO:b3jbdze) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L830)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Is this always true? What about for values?
</blockquote></details>

This is always true! `map_lex_unquoted_element` is called each time we want to lex a key or value, not on key/value pairs. Its caller (`parse_map_inner`) consumes the `=>` token. So if we ever see a `=>` without a key, we know that we've skipped lexing it somehow.
___
*[src/repr/src/strconv.rs, line 1072 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJuFHA9hV6rXbcC4IS:-MMNDO0d0CKBw99FGHDB:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L1072)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Maybe call this `MapValueWriter` since it only formats a single map value? Also I think the comment incorrectly states that it formats the key too.
</blockquote></details>

Done.
___
*[src/sql-parser/src/lexer.rs, line 63 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJw08CDtDyAUV2ZrC5:-MMNEktQ63qpyqUrR2_Z:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/sql-parser/src/lexer.rs#L63)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

=> 
</blockquote></details>

Done.
___
*[src/sql-parser/src/lexer.rs, line 138 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJxB7GB7OiJqSen9T_:-MMNE0Fd7UokDEnLLJ7g:b24l7v5) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/sql-parser/src/lexer.rs#L138)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This looks likely to break the gteq operator? I'd just let the lexer handle it the way it was handling it before...
</blockquote></details>

Ah yes, thanks!


<!-- Sent from Reviewable.io -->

2020-11-18 00:30 UTC, JLDLaughlin reviewed
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801)* status: 5 of 17 files reviewed, 18 unresolved discussions (waiting on @benesch and @sploiselle)

___
*[src/repr/src/strconv.rs, line 865 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJvI7XBB8XMAjzkRVb:-MMNi85oDZjGLi0_4sVa:b-f3072z) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L865)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It'd be really great if we could share this method with the list parsing code because it is so darn complicated. What do you think about just plumbing an `is_map` bool into that function? I think you can even leave `>` as a non-special char in the map case, because it only becomes special if it follows an `=` sign.
</blockquote></details>

Good point! I've updated this
___
*[src/repr/src/strconv.rs, line 880 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJu4ex0EhXc1Qk7cxJ:-MMNkOZQ94cOSlARg0rC:b-dtzbrh) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/repr/src/strconv.rs#L880)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This looks like it doesn't handle escaping the value?
</blockquote></details>

Yes! Fixed
___
*[src/sql/src/plan/typeconv.rs, line 647 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMK-Prc660Gr5QGJ1N2:-MMNkQTK2xNrUclJ6UJV:b4c9lyr) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/sql/src/plan/typeconv.rs#L647)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Leaving review of this hunk to @sploiselle!
</blockquote></details>

:thumbsup: 
___
*[test/sqllogictest/map.slt, line 54 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJxVKB8jL14HkYn9sg:-MMNkTAd3a7t2R4mLOBT:b-ldg2nj) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/test/sqllogictest/map.slt#L54)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

This looks like it needs escaping! 
</blockquote></details>

Have I addressed this issue?


<!-- Sent from Reviewable.io -->

2020-11-18 05:44 UTC, sploiselle requested changes
> Reviewed 7 of 7 files at r1, 1 of 9 files at r2, 12 of 12 files at r4, 6 of 7 files at r5.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801)* status: 10 of 17 files reviewed, 28 unresolved discussions (waiting on @benesch, @JLDLaughlin, and @sploiselle)

___
*[src/pgrepr/src/value.rs, line 474 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJqU-Z0YUe52vDTv_D:-MMOf3hD3qD87tTSpXws:bg2bc23) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/pgrepr/src/value.rs#L474)):*
<details><summary><i>Previously, JLDLaughlin (Jessica Laughlin) wrote…</i></summary><blockquote>

I remembered getting some sort of "key out of order" error, but I'm not able to reproduce it or find it now. The other issue is that the key/value pairs come back in any order without this sort, which makes asserting the value of multi-key maps impossible in tests.

Thinking about it, maybe this sorting hack should exist in sqllogictest instead?
</blockquote></details>

Have you seen sqllogictest's rowsort feature?

```
query I rowsort
SELECT a FROM t GROUP BY a HAVING sum(b) = 3
----
1
2
```
___
*[src/pgrepr/src/value.rs, line 569 at r4](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOffoRCn121AvGeZF7:-MMOffoRCn121AvGeZF8:b-5rag3q) ([raw file](https://github.com/materializeinc/materialize/blob/dbd950b3c34978753a7c6f63a4197677037bc407/src/pgrepr/src/value.rs#L569)):*
> ```Rust
>         },
>         Type::Map { value_type } => {
>             let (_, elem_type) = null_datum(value_type);
> ```

nit: alternating between "elem_type" here and "value_type" on the field
___
*[src/pgrepr/src/value.rs, line 202 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOhNTqAOMFz44eCxv8:-MMOhNTqAOMFz44eCxv9:bq3ckmz) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/pgrepr/src/value.rs#L202)):*
> ```Rust
>             }
>             Value::Map(map) => {
>                 let elem_pg_type = match typ {
> ```

nit: elem vs. value; I won't keep nitting this but would love to see all instance of elem that refer to the value switched to value
___
*[src/sql/src/plan/typeconv.rs, line 576 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOjAaZ0pu4K2ZuqfYc:-MMOjAaZ0pu4K2ZuqfYd:b-wfc5z4) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L576)):*
> ```Rust
> 
> /// Plans a cast between from a [`ScalarType::String`] to [`ScalarType::Map`].
> pub fn plan_cast_to_map(
> ```

Throughout this function (and transitively), instances of "element" should be changed to "value"; the element in a map is the pair `(k, v)` (in my mind, at least)
___
*[src/sql/src/plan/typeconv.rs, line 586 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOiYUxCb4bMHAi6J_F:-MMOiYUxCb4bMHAi6J_G:b-vlla) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L586)):*
> ```Rust
> 
>     if let ScalarExpr::CallUnary {
>         func: UnaryFunc::CastStringToMap { .. },
> ```

Does this allow something like this in spirit (realize this is not the actual syntax(:

```
SELECT 'some map str'::map::map
```

If so, what's the rationale behind that? If not, sorry that the expression is a little opaque to me--can I get a tl;dr on the invariant this is enforcing?
___
*[src/sql/src/plan/typeconv.rs, line 593 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOjXOC1VpjLaSyAMPv:-MMOjXOC1VpjLaSyAMPw:b-orz7vx) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L593)):*
> ```Rust
>     }
> 
>     let from_element_typ = match from {
> ```

Ah, the equivalent code in `plan_cast_to_list`was identifying which element you were casting from. In this case, you're only casting from string. This could just be reduced to:

```
if !matches!(from, ScalarType::String) {
 bail!("invalid cast from {} to map", from)
}
```

and then you can just `s/from_element_typ/from/` in the rest of this function 
___
*[src/sql/src/plan/typeconv.rs, line 628 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOks1g6Zv5rAgl0tlo:-MMOks1g6Zv5rAgl0tlp:bviz2o1) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L628)):*
> ```Rust
>     // Determine the `ScalarExpr` required to cast our column to the target
>     // element type. We'll need to call this on each element of the original
>     // list to perform the cast.
> ```

Did you sign the Materialize Code of Conduct? Looks like you plagarized my comment :smile:  The second sentence here needs to be modified.
___
*[src/sql/src/plan/typeconv.rs, line 640 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOlLlB0zmYRlhJoMT9:-MMOlLlB0zmYRlhJoMTA:b615p4e) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L640)):*
> ```Rust
>     ));
> 
>     Ok(expr.call_unary(match from {
> ```

Don't think you need the match on `from` here because there's only one condition
___
*[src/sql-parser/src/parser.rs, line 2136 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOmewZ8e41DfhA8GrP:-MMOmew_CtoLTvh62eM1:biil417) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql-parser/src/parser.rs#L2136)):*
> ```Rust
>                 JSON | JSONB => DataType::Jsonb,
>                 MAP => {
>                     let typ = self.parse_map()?;
> ```

I hate these kind of comments, but can we name `typ` here `value_type` to signal that the return type of `parse_map` is not a "Map type" but instead just the value type?
___
*[src/sql-parser/src/parser.rs, line 2342 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOr55_DYJz-XIBOcuX:-MMOr55_DYJz-XIBOcuY:brszrlu) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql-parser/src/parser.rs#L2342)):*
> ```Rust
>     }
> 
>     fn parse_map(&mut self) -> Result<DataType, ParserError> {
> ```

Is it possible to choke off support for nested map types here rather than in casting, or are they specifically only supported for string to map casting?
___
*[test/sqllogictest/map.slt, line 70 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOqjR83UEUKFGYbOaW:-MMOqjR83UEUKFGYbOaX:brpifsh) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/test/sqllogictest/map.slt#L70)):*
> ```
> 
> query error nested map types not yet supported
> SELECT '{a=>[b=>c]}'::map[text=>map[text=>text]]
> ```

Some more _really fun_ test cases I'd love to see:

- escaping `=>` in a string
- escaping spaces that don't get trimmed away at the end of strings, e.g. `SELECT '31=>  normal \ }'::map[text=>text]`
- escaping spaces preceded by trimmed white space, e.g. e.g. `SELECT '31=>  \ normal }'::map[text=>text]`


<!-- Sent from Reviewable.io -->

2020-11-18 05:45 UTC, sploiselle reviewed
Reviewable died on me mid-review and I'm off for the night. Will figure out where it died in the morning. Sorry if I ended up leaving comments you addressed in later commits, but didn't have a chance to reconcile them due to Reviewable's failure

> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801#-:-MMOsVmW9tMrrYh0DXyu:bpbz56t)* status: 10 of 17 files reviewed, 28 unresolved discussions (waiting on @benesch, @JLDLaughlin, and @sploiselle)



<!-- Sent from Reviewable.io -->

2020-11-18 16:12 UTC, sploiselle reviewed
Done reviewing; mostly just annoying comments about `element` vs `value`. Sorry!

> Reviewed 1 of 7 files at r5, 3 of 3 files at r6, 4 of 4 files at r7, 5 of 5 files at r8, 2 of 2 files at r9, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801#-:-MMR5hZf5lDBHWQhQ5j7:b-485ype)* status: all files reviewed, 31 unresolved discussions (waiting on @benesch, @JLDLaughlin, and @sploiselle)

___
*[src/expr/src/scalar/func.rs, line 3365 at r6](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR2ywy7T1t5-k1uLjX:-MMR2ywy7T1t5-k1uLjY:b-3n5gk1) ([raw file](https://github.com/materializeinc/materialize/blob/6ead934ce1e4999488f278d3ee776281b28bf31d/src/expr/src/scalar/func.rs#L3365)):*
> ```Rust
>         }),
>         Map { value_type } => {
>             use std::string::String;
> ```

Is this `use` necessary? Never seen that before.
___
*[src/repr/src/strconv.rs, line 627 at r9](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR4RfMEeyutAv5RgBf:-MMR4RfMEeyutAv5RgBg:b-83sjoh) ([raw file](https://github.com/materializeinc/materialize/blob/1406badb1788ca16a2a0864f75f0d9948cad9241/src/repr/src/strconv.rs#L627)):*
> ```Rust
> fn lex_unquoted_element<'a>(
>     buf: &mut LexBuf<'a>,
>     is_special_char: impl Fn(char) -> bool,
> ```

Nice!
___
*[src/sql/src/plan/typeconv.rs, line 576 at r7](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR6HUK9ZLLm8DM4Sp0:-MMR6HUK9ZLLm8DM4Sp1:b20o5t0) ([raw file](https://github.com/materializeinc/materialize/blob/05c8a3eb16ca67d6c8ad1233cd100a4954590e38/src/sql/src/plan/typeconv.rs#L576)):*
> ```Rust
> 
> /// Plans a cast between from a [`ScalarType::String`] to [`ScalarType::Map`].
> pub fn plan_cast_to_map(
> ```

Also, totally unnecessary, but just had the thought that `plan_cast_to_map` and `plan_cast_to_list` could be fused into something like `plan_iter_cast` because the meat of the code's the same; would just need to do a little type checking up front.


<!-- Sent from Reviewable.io -->

2020-11-18 16:40 UTC, benesch reviewed
Two last comments: one about escaping keys and one about the signature of `format_map`. After that it should be good to go from my perspective!

> Reviewed 5 of 12 files at r4, 2 of 4 files at r7, 3 of 5 files at r8, 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801#-:-MMRDY4G4-54KIQPGEaW:b-egm3u7)* status: all files reviewed, 19 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)

___
*[src/expr/src/scalar/func.rs, line 3315 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJzMbO6f8G3MSMYR2E:-MMRB3lMEZRGndZX-KWv:bl7baec) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/expr/src/scalar/func.rs#L3315)):*
<details><summary><i>Previously, JLDLaughlin (Jessica Laughlin) wrote…</i></summary><blockquote>

I was able to avoid creating the intermediate map in the other case! Fixing it in this case, and updating `format_map` to take `IntoIterator<Item = (&str, T)>` (instead of `IntoIterator<Item = (&'a String, T)>), would require introducing a `'a` lifetime for pgrepr's `Type`. I'm happy to do that, but it seemed like a decently large change.
</blockquote></details>

I think you can just do something like this?

```diff
diff --git a/src/expr/src/scalar/func.rs b/src/expr/src/scalar/func.rs
index edf81eb6a..a2752f3a4 100644
--- a/src/expr/src/scalar/func.rs
+++ b/src/expr/src/scalar/func.rs
@@ -9,7 +9,6 @@
 
 use std::borrow::Cow;
 use std::cmp::{self, Ordering};
-use std::collections::BTreeMap;
 use std::convert::{TryFrom, TryInto};
 use std::fmt;
 use std::iter;
@@ -3355,17 +3354,11 @@ where
             }
         }),
         Map { value_type } => {
-            use std::string::String;
-            let elems: BTreeMap<String, Datum> = d
-                .unwrap_dict()
-                .iter()
-                .map(|(k, v)| (k.to_owned(), v))
-                .collect();
-            strconv::format_map(buf, &elems, |buf, d| {
+            strconv::format_map(buf, &d.unwrap_dict(), |buf, d| {
                 if d.is_null() {
                     buf.write_null()
                 } else {
-                    stringify_datum(buf.nonnull_buffer(), *d, value_type)
+                    stringify_datum(buf.nonnull_buffer(), d, value_type)
                 }
             })
         }
diff --git a/src/repr/src/strconv.rs b/src/repr/src/strconv.rs
index 48809d6c7..00cd9996d 100644
--- a/src/repr/src/strconv.rs
+++ b/src/repr/src/strconv.rs
@@ -780,7 +780,7 @@ where
 
 pub fn format_map<'a, F, T>(
     buf: &mut F,
-    elems: impl IntoIterator<Item = (&'a String, T)>,
+    elems: impl IntoIterator<Item = (impl AsRef<str>, T)>,
     mut format_elem: impl FnMut(MapValueWriter<F>, T) -> Nestable,
 ) -> Nestable
 where
@@ -789,7 +789,7 @@ where
     buf.write_char('{');
     let mut elems = elems.into_iter().peekable();
     while let Some((key, value)) = elems.next() {
-        buf.write_str(key.as_str());
+        buf.write_str(key.as_ref());
         buf.write_str("=>");
         let start = buf.len();
         if let Nestable::MayNeedEscaping = format_elem(MapValueWriter(buf), value) {

```
___
*[src/pgrepr/src/value.rs, line 474 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJqU-Z0YUe52vDTv_D:-MMR8IbY7WGjlDzDY97P:bqj5b33) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/pgrepr/src/value.rs#L474)):*
I think the problem is that if the textual output format of a map is unstable, then row sort doesn't help you. Like I think this is valid output if using a hashmap:

```
> CREATE TABLE t (a map[text => int]);
> INSERT INTO t VALUES ('a => 1, b => 2');
> INSERT INTO t VALUES ('a => 1, b => 2');
> SELECT * FROM t;
a
----
{a => 1, b => 2}
{b => 2, a => 1}
```

As is:

```
> SELECT * FROM t
a
----
{a => 1, b => 2}
{a => 1, b => 2}
```
___
*[src/repr/src/scalar.rs, line 332 at r10](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR9twvBRxcntR09m-C:-MMR9twvBRxcntR09m-D:b9wwsps) ([raw file](https://github.com/materializeinc/materialize/blob/fc24757eadace99ac9a39d2c39761c1751afa25b/src/repr/src/scalar.rs#L332)):*
> ```Rust
>     /// Panics if the datum is not [`Datum::Dict`].
>     #[track_caller]
>     pub fn unwrap_dict(&self) -> DatumMap<'a> {
> ```

Oh, just realized this method should be renamed to `unwrap_map`.
___
*[src/repr/src/strconv.rs, line 627 at r9](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR4RfMEeyutAv5RgBf:-MMR98UU6_MeoLToXspt:b-pbdqzg) ([raw file](https://github.com/materializeinc/materialize/blob/1406badb1788ca16a2a0864f75f0d9948cad9241/src/repr/src/strconv.rs#L627)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

Agreed!
___
*[src/repr/src/strconv.rs, line 792 at r10](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMRCbtG1wdLlDJelY_P:-MMRCbtHC8L3bce5X5E6:bey0g99) ([raw file](https://github.com/materializeinc/materialize/blob/fc24757eadace99ac9a39d2c39761c1751afa25b/src/repr/src/strconv.rs#L792)):*
> ```Rust
>     let mut elems = elems.into_iter().peekable();
>     while let Some((key, value)) = elems.next() {
>         buf.write_str(key.as_str());
> ```

Left you a note down in the test file below, but the key also needs to go through `escape_elem`.
___
*[src/sql-parser/src/lexer.rs, line 138 at r3](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJxB7GB7OiJqSen9T_:-MMRD0w73cxBPmvWR4oO:bmikhzb) ([raw file](https://github.com/materializeinc/materialize/blob/195deb8afe28d20b61f766d32250797a1b58069d/src/sql-parser/src/lexer.rs#L138)):*
<details><summary><i>Previously, JLDLaughlin (Jessica Laughlin) wrote…</i></summary><blockquote>

Ah yes, thanks!
</blockquote></details>

Oops, forgot to end with "...and just look for the operator in the parser" but that's exactly what you did! :+1: 
___
*[test/sqllogictest/map.slt, line 24 at r10](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMRBxLa2n37GMjzOIgl:-MMRBxLa2n37GMjzOIgm:b-7c52j6) ([raw file](https://github.com/materializeinc/materialize/blob/fc24757eadace99ac9a39d2c39761c1751afa25b/test/sqllogictest/map.slt#L24)):*
> ```
> CREATE TYPE custom AS MAP (key_type=text, value_type=bool)
> 
> query error
> ```

Can you add the expected error text here? Otherwise it's easy for some _other_ error to get introduced, and this won't end up testing what you think it is.
___
*[test/sqllogictest/map.slt, line 54 at r10](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMRCLbjB0nW079mnjp7:-MMRCLbjB0nW079mnjp8:b-izamuy) ([raw file](https://github.com/materializeinc/materialize/blob/fc24757eadace99ac9a39d2c39761c1751afa25b/test/sqllogictest/map.slt#L54)):*
> ```
> SELECT '{a\=\>=>2}'::map[text=>int]
> ----
> {a=>=>2}
> ```

This output isn't actually a valid map. Need to escape the keys too, looks like!


<!-- Sent from Reviewable.io -->

2020-11-19 00:14 UTC, JLDLaughlin reviewed
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801)* status: 9 of 18 files reviewed, 17 unresolved discussions (waiting on @benesch, @JLDLaughlin, and @sploiselle)

___
*[src/expr/src/scalar/func.rs, line 3315 at r2](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMJzMbO6f8G3MSMYR2E:-MMSHbNv-mBmYmYIEA8K:b8d12jo) ([raw file](https://github.com/materializeinc/materialize/blob/07a2fdacb62e19d9b0d526853f58929f4ade6669/src/expr/src/scalar/func.rs#L3315)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I think you can just do something like this?

```diff
diff --git a/src/expr/src/scalar/func.rs b/src/expr/src/scalar/func.rs
index edf81eb6a..a2752f3a4 100644
--- a/src/expr/src/scalar/func.rs
+++ b/src/expr/src/scalar/func.rs
@@ -9,7 +9,6 @@
 
 use std::borrow::Cow;
 use std::cmp::{self, Ordering};
-use std::collections::BTreeMap;
 use std::convert::{TryFrom, TryInto};
 use std::fmt;
 use std::iter;
@@ -3355,17 +3354,11 @@ where
             }
         }),
         Map { value_type } => {
-            use std::string::String;
-            let elems: BTreeMap<String, Datum> = d
-                .unwrap_dict()
-                .iter()
-                .map(|(k, v)| (k.to_owned(), v))
-                .collect();
-            strconv::format_map(buf, &elems, |buf, d| {
+            strconv::format_map(buf, &d.unwrap_dict(), |buf, d| {
                 if d.is_null() {
                     buf.write_null()
                 } else {
-                    stringify_datum(buf.nonnull_buffer(), *d, value_type)
+                    stringify_datum(buf.nonnull_buffer(), d, value_type)
                 }
             })
         }
diff --git a/src/repr/src/strconv.rs b/src/repr/src/strconv.rs
index 48809d6c7..00cd9996d 100644
--- a/src/repr/src/strconv.rs
+++ b/src/repr/src/strconv.rs
@@ -780,7 +780,7 @@ where
 
 pub fn format_map<'a, F, T>(
     buf: &mut F,
-    elems: impl IntoIterator<Item = (&'a String, T)>,
+    elems: impl IntoIterator<Item = (impl AsRef<str>, T)>,
     mut format_elem: impl FnMut(MapValueWriter<F>, T) -> Nestable,
 ) -> Nestable
 where
@@ -789,7 +789,7 @@ where
     buf.write_char('{');
     let mut elems = elems.into_iter().peekable();
     while let Some((key, value)) = elems.next() {
-        buf.write_str(key.as_str());
+        buf.write_str(key.as_ref());
         buf.write_str("=>");
         let start = buf.len();
         if let Nestable::MayNeedEscaping = format_elem(MapValueWriter(buf), value) {

```
</blockquote></details>

Ah - yes, that works!
___
*[src/expr/src/scalar/func.rs, line 3365 at r6](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR2ywy7T1t5-k1uLjX:-MMR8Vpq6fsy1JslYvAw:b-2r5ti) ([raw file](https://github.com/materializeinc/materialize/blob/6ead934ce1e4999488f278d3ee776281b28bf31d/src/expr/src/scalar/func.rs#L3365)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Is this `use` necessary? Never seen that before.
</blockquote></details>

It was because the unqualified `String` was pointing to `ScalarType::String`! (This is no longer necessary once I take Nikhil's suggestion.)
___
*[src/repr/src/scalar.rs, line 332 at r10](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR9twvBRxcntR09m-C:-MMSIEWAErvHWTavOyja:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/fc24757eadace99ac9a39d2c39761c1751afa25b/src/repr/src/scalar.rs#L332)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Oh, just realized this method should be renamed to `unwrap_map`.
</blockquote></details>

Done.
___
*[src/repr/src/strconv.rs, line 627 at r9](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR4RfMEeyutAv5RgBf:-MMR9nLD1SsqKYHeJrdb:b7kysz1) ([raw file](https://github.com/materializeinc/materialize/blob/1406badb1788ca16a2a0864f75f0d9948cad9241/src/repr/src/strconv.rs#L627)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

It was all teamwork!
___
*[src/repr/src/strconv.rs, line 792 at r10](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMRCbtG1wdLlDJelY_P:-MMSKPWlEG6TXZ3194C-:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/fc24757eadace99ac9a39d2c39761c1751afa25b/src/repr/src/strconv.rs#L792)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Left you a note down in the test file below, but the key also needs to go through `escape_elem`.
</blockquote></details>

Done.
___
*[src/sql/src/plan/typeconv.rs, line 576 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOjAaZ0pu4K2ZuqfYc:-MMSKggt7FM79PX2aymi:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L576)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Throughout this function (and transitively), instances of "element" should be changed to "value"; the element in a map is the pair `(k, v)` (in my mind, at least)
</blockquote></details>

Done.
___
*[src/sql/src/plan/typeconv.rs, line 593 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOjXOC1VpjLaSyAMPv:-MMSLasH8KhzG3ZzdYPA:b-x7qjbl) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L593)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Ah, the equivalent code in `plan_cast_to_list`was identifying which element you were casting from. In this case, you're only casting from string. This could just be reduced to:

```
if !matches!(from, ScalarType::String) {
 bail!("invalid cast from {} to map", from)
}
```

and then you can just `s/from_element_typ/from/` in the rest of this function 
</blockquote></details>

So what I found was that `plan_expr` actually calls `plan_cast` twice for `Expr::Cast`s: once to generate a `CoercibleScalarExpr` and again to actually plan the cast. 

In the case of casting from a string to a map, calling `plan_cast` twice  (and therefore `plan_cast_to_map` twice) was creating the wrong cast. The `if let` check above ensures that we will only generate the map cast expression once. The second time its called, it just returns.

Alternatively, I could write a `plan_map` function like `plan_list`, instead.
___
*[src/sql/src/plan/typeconv.rs, line 628 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOks1g6Zv5rAgl0tlo:-MMRAZ3q4psdXHgLLj1S:b-8hmwt) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L628)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Did you sign the Materialize Code of Conduct? Looks like you plagarized my comment :smile:  The second sentence here needs to be modified.
</blockquote></details>

A true gotcha moment - fixing!
___
*[src/sql/src/plan/typeconv.rs, line 640 at r5](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMOlLlB0zmYRlhJoMT9:-MMSN7kJ9kW0lbkIyMiE:b-896fix) ([raw file](https://github.com/materializeinc/materialize/blob/f48277ac22c4a5683df5b16b12a242401d8062f2/src/sql/src/plan/typeconv.rs#L640)):*
<details><summary><i>Previously, sploiselle (Sean Loiselle) wrote…</i></summary><blockquote>

Don't think you need the match on `from` here because there's only one condition
</blockquote></details>

Done.
___
*[src/sql/src/plan/typeconv.rs, line 576 at r7](https://reviewable.io/reviews/materializeinc/materialize/4801#-MMR6HUK9ZLLm8DM4Sp0:-MMSRloT7s41Reh9S9jz:b-h07qif) ([raw file](https://github.com/materializeinc/materialize/blob/05c8a3eb16ca67d6c8ad1233cd100a4954590e38/src/sql/src/plan/typeconv.rs#L576)):*
<details><summary>< [...]

2020-11-19 05:33 UTC, benesch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 9 of 9 files at r11.
> *[Reviewable](https://reviewable.io/reviews/materializeinc/materialize/4801#-:-MMTzOvoANMZ6stIFLrF:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @JLDLaughlin and @sploiselle)



<!-- Sent from Reviewable.io -->

2020-11-19 18:33 UTC, sploiselle commented
LGTM!

2020-11-19 19:51 UTC, merged