testdrive: Print sql up to the term width, instead of only 72 chars
MaterializeInc/materialize pull request #8401
Opened 2021-09-23 13:42 UTC by quodlibetor

72 characters is pretty short for most materialized views, this makes many
things easier to see while still keeping the testdrive output clearly readable.

2021-09-28 00:19 UTC, benesch requested changes
I've actually been thinking that chopping these queries at all was a mistake. WDYT about instead just always printing the full query?

2021-09-29 13:28 UTC, philip-stoev approved these changes
This would be very useful.

If you decide to go with @benesch's suggestion, can we print the raw SQL query as it was in the .td file, newlines, spaces and all? Or those are lost by the time we print?

2021-09-29 18:04 UTC, quodlibetor commented
> can we print the raw SQL query as it was in the .td file, newlines, spaces and all? Or those are lost by the time we print?

They are lost by the time we want to print this, which is my biggest hesitation about printing the whole thing right now, some of the SQL gets very long. I'd be happier to do that in CI, but I'm considering playing with @mjibson's mzfmt in testdrive on a Friday.

2021-09-29 18:06 UTC, benesch commented
It's fine if the SQL is long. I'd really like to avoid adding much complexity here. testdrive is an internal tool, and it's ok if the output has some minor defects if it makes the code simpler.

2021-12-06 22:53 UTC, closed without merging