qgm: add typ method in BoxScalarExpr
MaterializeInc/materialize pull request #9917
Opened 2022-01-05 21:40 UTC by asenac

Closes ##9601

### Motivation

### Tips for reviewer

### Checklist

- [ ] This PR has adequate test coverage / QA involvement has been duly considered.
- [ ] This PR adds a release note for any [user-facing behavior changes](https://github.com/MaterializeInc/materialize/blob/main/doc/user/content/release-notes.md#what-changes-require-a-release-note).

2022-01-07 10:24 UTC, asenac commented
BTW, we should add the ID when printing Get operators and use the humanizer to print them.

2022-01-14 18:00 UTC, aalexandrov requested changes

2022-01-14 18:00 UTC, aalexandrov commented on src/sql/src/query_model/mod.rs
> +    /// Returns the type of a given column projected by this box.
Another query that is not working is:

```sql
SELECT coalesce(x, y) FROM T WHERE x IS NOT NULL
```
![typed-query-graph-q2](https://user-images.githubusercontent.com/1071946/149562985-f25a8965-b677-48f0-b876-f02e13c97792.png)

2022-01-14 18:12 UTC, aalexandrov commented on src/sql/src/query_model/mod.rs
> +                    for predicate in select.predicates.iter() {
I don't think we should be calling `BoxScalarExpr::non_null_requirements` on the predicate expressions in order to infer columns that will be rejected if null.

For example, for the `x IS NOT NULL` fragment in

```sql
SELECT coalesce(x, y) FROM T WHERE x IS NOT NULL
```
the corresponding `non_null_requirements` returns an empty set, whereas I would intuitively expect it to return `x`.

2022-01-24 22:01 UTC, closed without merging